pre-release fixes

diff --git a/main/functions b/main/functions
--- a/main/functions
+++ b/main/functions
@@ -26,7 +26,7 @@ ls
 printf "\n%s\n\n" "Run any tool with the '-h' parameter to see help"
 printf "\n%s\n\n" "Run any tool without parameters to execute their default function"
 printf "%s\n\n" "Return to the PieHelper menu by typing 'exit' or CTRL-D"
-/bin/bash +x
+/bin/bash
 return 0
 }
 
@@ -128,8 +128,7 @@ typeset PH_APP="Moonlight"
 typeset -i PH_COUNT=0
 
 printf "%s\n" "- Pairing with $PH_MOON_SRV"
-printf "%2s%s\n" "" "Please enter the PIN generated by this command in the SHIELD popup window on local network server $PH_MOON_SRV"
-if moonlight pair $PH_MOON_SRV
+if moonlight pair $PH_MOON_SRV 2>&1 | nawk '{ printf "%2s%s\n", "", $0 }'
 then
 	printf "%2s%s\n" "" "SUCCESS"
 else
@@ -429,7 +428,7 @@ then
 else
 	if [[ "$PH_TYPE" == "integrated" ]]
 	then
-		ph_check_app_name -s -a "$PH_RUNAPP" >/dev/null 2>&1
+		ph_check_app_name -s -a "$PH_APP" >/dev/null 2>&1
 		[[ $? -ne 0 ]] && printf "%2s%s\n" "" "FAILED : Unknown $PH_TYPE application \"$PH_APP\" -> Not a supported application" || \
 			(printf "%2s%s\n" "" "FAILED : Application is still uninstalled or undiscovered" ; printf "%11s%s\n" "" "Both the PieHelper menu and the 'confapps_ph.sh' tool can be used for either installing the application or running a discovery scan")
 	else
@@ -570,7 +569,7 @@ do
 	if [[ "$1" == "Apps" ]]
 	then
 		>$PH_FILES_DIR/menus/Apps.lst
-		for PH_j in `nawk '{ print $1 }' $PH_CONF_DIR/installed_apps`
+		for PH_j in `nawk '{ print $1 }' $PH_CONF_DIR/supported_apps`
 		do
 			echo "Go to $PH_j submenu:ph_show_menu $PH_j" >>$PH_FILES_DIR/menus/Apps.lst
 		done
@@ -1212,7 +1211,7 @@ printf "%8s%s\n" "" "--> Checking for a package name"
 if [[ -n `eval echo \\$PH_"$PH_APPU"_PKG_NAME` ]]
 then
 	printf "%10s%s\n" "" "OK (Found)"
-	printf "%8s%s\n" "" "--> Installing `eval echo \\$PH_"$PH_APPU"_PKG_NAME` package"
+	printf "%8s%s\n" "" "--> Installing `eval echo \\$PH_"$PH_APPU"_PKG_NAME` package (This may take a while)"
 	if ! ph_install_pkg `eval echo \\$PH_"$PH_APPU"_PKG_NAME`
 	then
 		printf "%10s%s\n" "" "Warning : Could not install `eval echo \\$PH_"$PH_APPU"_PKG_NAME` package"
@@ -1231,7 +1230,7 @@ case $PH_APP in Moonlight)
 		printf "%10s%s\n" "" "OK ($PH_APP)"
 		cd >/dev/null
 		$PH_SUDO rm -r moonlight-embedded 2>/dev/null
-		rm /tmp/$PH_APP.compile 2>/dev/null
+		rm /tmp/"$PH_APP".compile /tmp/"$PH_APP".generate 2>/dev/null
 		printf "%8s%s\n" "" "--> Downloading $PH_APP source"
 		git clone https://github.com/irtimmer/moonlight-embedded.git >/dev/null 2>&1
 		[[ $? -eq 0 ]] && printf "%10s%s\n" "" "OK" || (printf "%10s%s\n" "" "ERROR : Could not download Moonlight source" ; \
@@ -1240,17 +1239,43 @@ case $PH_APP in Moonlight)
 		git submodule update --init >/dev/null 2>&1
 		mkdir build
 		cd build/
-		printf "%8s%s\n" "" "--> Attempting to compile $PH_APP source (This may take a while)"
-		cmake ../ >>/tmp/$PH_APP.compile 2>&1
-		[[ $? -ne 0 ]] && printf "%10s%s\n" "" "ERROR : Could not compile $PH_APP source" && \
-					printf "%18s%s\n" "" "- The log for the compile attempt is /tmp/$PH_APP.compile" && \
-					printf "%2s%s\n" "" "FAILED" && return 1
-		make >>/tmp/$PH_APP.compile 2>&1
-		[[ $? -ne 0 ]] && printf "%10s%s\n" "" "ERROR : Could not compile $PH_APP source" && \
-					printf "%18s%s\n" "" "- The log for the compile attempt is /tmp/$PH_APP.compile" && \
-					printf "%2s%s\n" "" "FAILED" && return 1
+		printf "%8s%s\n" "" "--> Attempting to generate build for $PH_APP source (This may take a while)"
+		cmake ../ >/tmp/"$PH_APP".generate 2>&1
+		if [[ $? -ne 0 ]]
+		then
+			printf "%10s%s\n" "" "ERROR : Could not compile $PH_APP source"
+			printf "%18s%s\n" "" "The log for the build generation is /tmp/$PH_APP.generate"
+			printf "%8s%s\n" "" "--> Displaying build generation log (Press 'q' to quit)"
+			printf "%10s%s\n\n" "" "OK"
+			ph_print_bannerline
+			printf "\n"
+			less /tmp/"$PH_APP".generate
+			printf "\n"
+			ph_print_bannerline
+			printf "\n"
+			printf "%2s%s\n" "" "FAILED"
+			return 1
+		fi
 		printf "%10s%s\n" "" "OK"
-		rm /tmp/$PH_APP.compile 2>/dev/null
+		printf "%8s%s\n" "" "--> Attempting to compile $PH_APP source (This may take a while)"
+		make >/tmp/"$PH_APP".compile 2>&1
+		if [[ $? -ne 0 ]]
+		then
+			printf "%10s%s\n" "" "ERROR : Could not compile $PH_APP source"
+			printf "%18s%s\n" "" "The log for the compile attempt is /tmp/$PH_APP.compile"
+			printf "%8s%s\n" "" "--> Displaying compilation log (Press 'q' to quit)"
+			printf "%10s%s\n\n" "" "OK"
+			ph_print_bannerline
+			printf "\n"
+			less /tmp/"$PH_APP".compile
+			printf "\n"
+			ph_print_bannerline
+			printf "\n"
+			printf "%2s%s\n" "" "FAILED"
+			return 1
+		fi
+		printf "%10s%s\n" "" "OK"
+		rm /tmp/"$PH_APP".compile /tmp/"$PH_APP".generate 2>/dev/null
 		printf "%8s%s\n" "" "--> Copying files to final locations"
 		$PH_SUDO make install >/dev/null
 		printf "%10s%s\n" "" "OK" ;;
@@ -1266,6 +1291,7 @@ case $PH_APP in Moonlight)
 		$PH_SUDO chmod +x retropie_setup.sh
 		printf "%8s%s\n" "" "--> Executing $PH_APP setup script"
 		printf "%12s%s\n" "" "- Use this setup script to do a basic install of $PH_APP"
+		printf "%14s%s\n" "" "Note that running basic install could take up to 30 minutes depending on your current system configuration"
 		printf "%12s%s\n" "" "- Settings for autostart configured with this script will be overridden by PieHelper"
 		printf "%12s%s\n" "" "- Exit the script normally after it finishes and PieHelper integration will resume"
 		printf "%12s%s\n" "" "Press Enter to continue"
@@ -1287,7 +1313,7 @@ case $PH_APP in Moonlight)
 		fi
 		PH_EMUL_SETUP_DIR="$HOME/RetroPie"
 		ph_set_option $PH_APP -r PH_EMUL_SETUP_DIR="$PH_EMUL_SETUP_DIR" || return $?
-		[[ -z "$PH_EMUL_DIR" ]] && printf "%10s%s\n" "" "Warning : Could not determine $PH_APP base directory" && \
+		[[ -z "$PH_EMUL_SETUP_DIR" ]] && printf "%10s%s\n" "" "Warning : Could not determine $PH_APP base directory" && \
 					printf "%20s%s\n" "" "Try manually setting PH_EMUL_DIR to the correct value using confopts_ph.sh or the PieHelper menu"
 					printf "%2s%s\n" "" "FAILED" && return 1
 		ph_set_option $PH_APP -r PH_EMUL_DIR="$PH_EMUL_DIR" || return $?
@@ -1480,7 +1506,7 @@ then
 			printf "%10s%s\n" "" "OK"
 			printf "%8s%s\n" "" "--> Creating user $PH_APP_USER"
 			$PH_SUDO useradd -d /home/$PH_APP_USER -c "${PH_APP_READ[$PH_i]} application" -g $PH_APP_USER \
-							-G tty,audio,video -s /bin/bash $PH_APP_USER >/dev/null 2>&1
+							-G tty,audio,video,input -s /bin/bash $PH_APP_USER >/dev/null 2>&1
 			printf "%10s%s\n" "" "OK"
 		fi
 		break
@@ -2088,10 +2114,10 @@ printf "%8s%s\n" "" "--> Displaying TTY warning"
 printf "%10s%s\n\n" "" "OK"
 ph_print_bannerline
 printf "\n"
-printf "%8s%s\n\n" "" "PieHelper works by changing the default configuration of your TTY's"
-printf "%8s%s\n" "" "- If you have already made custom changes to your system's TTY setup you should remove them before configuring PieHelper"
+printf "%8s%s\n\n" "" "PieHelper works by changing the default configuration of your TTYs"
+printf "%8s%s\n" "" "- If you have already made custom changes to your system's TTY setup you should exit now and remove them before configuring PieHelper"
 printf "%10s%s\n" "" "Any custom packaged applications you want to autostart can later be integrated into PieHelper"
-printf "%8s%s\n\n" "" "- If you have no custom TTY setup or have no idea what TTY's are, you should be safe"
+printf "%8s%s\n\n" "" "- If you have no custom TTY setups or have no idea what TTYs are, you should be safe"
 ph_print_bannerline
 printf "\n"
 while [[ "$PH_ANSWER" != @(y|n) ]]
@@ -2110,6 +2136,10 @@ then
 	printf "%8s%s\n" "" "--> Checking for sudo rights for user \"$PH_RUN_USER\""
 	if [[ -n "$PH_SUDO" ]]
 	then
+		printf "%10s%s\n" "" "OK"
+		printf "%8s%s\n" "" "--> Adding additional secondary groups for user \"$PH_RUN_USER\""
+		$PH_SUDO usermod -G tty,audio,video,input "$PH_RUN_USER" >/dev/null 2>&1 || (printf "%10s%s\n" "" "ERROR : Could not add additional secondary groups for $PH_RUN_USER" ; \
+					printf "%2s%s\n" "" "FAILED" ; return 1) || return $?
 		printf "%10s%s\n" "" "OK"
 	else
 		printf "%10s%s\n" "" "ERROR : PieHelper needs administrative rights to function"
@@ -2144,6 +2174,8 @@ do
 		ph_install_pkg $PH_i && printf "%10s%s\n" "" "OK" || (printf "%10s%s\n" "" "ERROR : Could not install required package $PH_i" ; \
 								ph_set_default_tty_states ; ph_set_default_logind_conf ; \
 								printf "%2s%s\n" "" "FAILED" ; return 1) || return $?
+	else
+		printf "%10s%s\n" "" "OK (Already installed)"
 	fi
 done
 ## check if following needed and implement error handling
@@ -2247,18 +2279,23 @@ printf "%10s%s\n\n" "" "OK"
 ph_print_bannerline
 printf "\n\n%8s%s\n\n" "" "PieHelper allows easy switching between it's integrated applications"
 printf "%8s%s\n" "" "-> If you're connected over the network you can use the scripts available in $PH_SCRIPTS_DIR"
-printf "%8s%s\n\n" "" "-> If you're connected directly you can press Ctrl-LeftAlt-Functionkey#TTY"
-ph_print_bannerline
-printf "\n\n%8s%s\n\n" "" "Any applications that do not render to the default frame buffer"
-printf "%8s%s\n" "" "such as Emulationstation, Moonlight and Kodi need to be quit manually first when switching TTY's"
-printf "%8s%s\n" "" "to an application marked as persistent if you're not controlling your Pi from a pseudoterminal"
-printf "%8s%s\n\n" "" "Alternatively, persistence can be switched off for both applications"
+printf "%8s%s\n" "" "-> If you're connected directly you can use the linux built-in keycombo of Ctrl-LeftAlt-Functionkey#TTY"
+printf "%11s%s\n\n" "" "For direct control with a mouse and keyboard, the following notes apply :"
+printf "%11s%s\n" "" "- Any applications that do not render to the default frame buffer need to be quit first before switching TTYs if"
+printf "%13s%s\n" "" "the application that is being switched to is marked as persistent"
+printf "%13s%s\n" "" "Neither should these types of applications be marked as persistent themselves"
+printf "%13s%s\n" "" "More info on persistence can be found in the HOWTO"
+printf "%13s%s\n" "" "Examples are Moonlight, Kodi and Emulationstation"
+printf "%11s%s\n" "" "- Any application that intercepts and interprets the keycombo for TTY switching itself always have to be quit before switching TTYs"
+printf "%13s%s\n" "" "Examples are Moonlight and Kodi"
+printf "\n"
 ph_print_bannerline
 printf "\n%2s%s\n" "" "SUCCESS"
 rm $PH_FILES_DIR/first_run 2>/dev/null
 printf "\n%s" "Press Enter to reboot and continue"
 read 2>/dev/null
 $PH_SUDO init 6
+return 0
 }
 
 function ph_run_app_action {
@@ -2325,15 +2362,14 @@ case $1 in start)
 	PH_RUNAPP_TTY=`ph_get_tty_for_app $PH_RUNAPP`
 	PH_RUNAPP_CMD=`nawk -v runapp=^"$PH_RUNAPP"$ 'BEGIN { ORS=" " } $1 ~ runapp { for (i=2;i<=NF;i++) { if (i==NF) { ORS="" ; print $i } else { print $i }}}' $PH_CONF_DIR/supported_apps`
 	PH_RUNAPP_CMD=`sed "s/PH_TTY/$PH_RUNAPP_TTY/" <<<$PH_RUNAPP_CMD`
-	if [[ "$PH_RUNAPP" == "PieHelper" ]]
-	then
-		PH_RUNAPP_CMD="ph_show_menu"
-	fi
+	[[ "$PH_RUNAPP" == "PieHelper" ]] && PH_RUNAPP_CMD="ph_show_menu"
+	[[ "$PH_RUNAPP" == "Moonlight" ]] && PH_RUNAPPU_CMD_OPTS="`echo -n $PH_RUNAPPU_CMD_OPTS` $PH_MOON_SRV"
 	printf "%8s%s\n" "" "--> Starting $PH_RUNAPP"
 	$PH_SUDO systemctl start getty@tty$PH_RUNAPP_TTY >/dev/null 2>&1
-	[[ `fgconsole` -eq $PH_RUNAPP_TTY && "$PH_RUNAPP_CMD" != "/bin/bash" ]] && eval $PH_RUNAPP_CMD $PH_RUNAPPU_CMD_OPTS 2>/dev/null || $PH_SUDO `which chvt` $PH_RUNAPP_TTY
+	[[ `$PH_SUDO fgconsole` -eq $PH_RUNAPP_TTY && "$PH_RUNAPP_CMD" != "/bin/bash" ]] && eval $PH_RUNAPP_CMD $PH_RUNAPPU_CMD_OPTS || $PH_SUDO `which chvt` $PH_RUNAPP_TTY
 	[[ $? -ne 0 ]] && unset -n PH_RUNAPPU_CMD_OPTS PH_RUNAPPU_NUM_CTRL && printf "%10s%s\n" "" "ERROR : Could not start $PH_RUNAPP" && return 1
 	unset -n PH_RUNAPPU_CMD_OPTS PH_RUNAPPU_NUM_CTRL
+	[[ "$PH_RUNAPP" == "PieHelper" ]] && exit 0
 	printf "%10s%s\n" "" "OK"
 	if [[ "$PH_RUNAPP" == "Bash" ]]
 	then
@@ -2348,18 +2384,18 @@ case $1 in start)
 		printf "%10s%s\n" "" "Warning : $PH_RUNAPP is marked persistent -> Staying online" && return 0
 	fi
 	PH_RUNAPP_TTY=`ph_get_tty_for_app $PH_RUNAPP`
-	if [[ `fgconsole` -eq $PH_RUNAPP_TTY && "$PH_RUNAPP" != "PieHelper" ]]
+	if [[ `$PH_SUDO fgconsole` -eq $PH_RUNAPP_TTY && "$PH_RUNAPP" != "PieHelper" ]]
 	then
 		PH_PIEH_TTY=`ph_get_tty_for_app PieHelper`
 		if [[ ($? -ne 0) && ($PH_PIEH_TTY -le $PH_PIEH_MAX_TTYS && $PH_PIEH_TTY -gt 0) ]]
 		then
-			pgrep -t $PH_PIEH_TTY startpieh.sh >/dev/null && $PH_SUDO `which chvt` $PH_PIEH_TTY || \
+			pgrep -t tty$PH_PIEH_TTY "startpieh.sh" >/dev/null && $PH_SUDO `which chvt` $PH_PIEH_TTY || \
 										$PH_SUDO `which chvt` 1
 		else
 			$PH_SUDO `which chvt` 1
 		fi
 	else
-		[[ "$PH_RUNAPP" == "PieHelper" && `fgconsole` -eq $PH_RUNAPP_TTY ]] && $PH_SUDO `which chvt` 1
+		[[ "$PH_RUNAPP" == "PieHelper" && `$PH_SUDO fgconsole` -eq $PH_RUNAPP_TTY ]] && $PH_SUDO `which chvt` 1
 	fi
 	printf "%10s%s\n" "" "OK"
 	$PH_SUDO systemctl stop getty@tty$PH_RUNAPP_TTY >/dev/null 2>&1
