fix for moonlight pairing

diff --git a/main/functions b/main/functions
--- a/main/functions
+++ b/main/functions
@@ -17,6 +17,67 @@ done
 return 0
 }
 
+function ph_configure_moon {
+
+typeset PH_ANSWER=""
+typeset PH_APP="Moonlight"
+typeset -i PH_COUNT=0
+typeset -i PH_OPT=0
+set -A PH_OPTAR PH_MOON_RES PH_MOON_FPS PH_MOON_BITRATE PH_MOON_PCKTSIZE PH_MOON_USE_CTRL PH_MOON_NUM_CTRL PH_MOON_CMD_OPTS PH_MOON_GAME PH_MOON_SRV
+
+for PH_OPT in {0..$((${#PH_OPTAR[@]}-1))}
+do
+        PH_COUNT=0
+        confopts_ph.sh -p get -a Moonlight -o "${PH_OPTAR[$PH_OPT]}" | tail -n +3
+        confopts_ph.sh -p help -a Moonlight -o "${PH_OPTAR[$PH_OPT]}" | tail -n +3
+        printf "%s\n" "- Prompting for requested change"
+        while [[ $PH_ANSWER != @(y|n) ]]
+        do
+                [[ $PH_COUNT -gt 0 ]] && printf "\n%10s%s\n\n" "" "ERROR : Invalid response"
+                printf "%8s%s" "" "--> Do you want the change the value for ${PH_OPTAR[$PH_OPT]} (y/n) ? "
+                [[ "${PH_OPTAR[$PH_OPT]}" == "PH_MOON_SRV" ]] && (printf "\n\n%12s%s\n" "" "- A value for PH_MOON_SRV is required for further configuration" ; \
+                                printf "%12s%s" "" "- An empty value for PH_MOON_SRV will end configuration but it can later be restarted using either 'confapps_ph.sh' or the PieHelper menu : ")
+                read PH_ANSWER 2>/dev/null
+                if ! ph_screen_input $PH_ANSWER
+                then
+                        unset PH_OPTAR
+                        return 1
+                fi
+                ((PH_COUNT++))
+        done
+        [[ "${PH_OPTAR[$PH_OPT]}" == "PH_MOON_SRV" ]] && printf "\n%10s%s\n" "" "OK" || printf "%10s%s\n" "" "OK"
+        if [[ "$PH_ANSWER" == "y" ]]
+        then
+                false
+                while [[ $? -ne 0 ]]
+                do
+                        [[ "$PH_ANSWER" != "y" ]] && printf "%s\n" "- Prompting for requested change"
+                        PH_ANSWER=""
+                        while [[ "$PH_ANSWER" == "" ]]
+                        do
+                                printf "%8s%s" "" "--> Please enter the new value for ${PH_OPTAR[$PH_OPT]} : "
+                                read PH_ANSWER 2>/dev/null
+                                [[ "$PH_i" == "PH_MOON_GAME" ]] && break
+                        done
+                        printf "%10s%s\n" "" "OK"
+                        ph_set_option Moonlight -r "${PH_OPTAR[$PH_OPT]}"="$PH_ANSWER" && printf "%2s%s\n" "" "SUCCESS" || printf "%2s%s\n" "" "FAILED"
+                done
+        else
+                printf "%2s%s\n" "" "SUCCESS"
+                if [[ "${PH_OPTAR[$PH_OPT]}" == "PH_MOON_SRV" && -z "$PH_MOON_SRV" ]]
+                then
+                        unset PH_OPTAR
+                        return 0
+                fi
+        fi
+        PH_ANSWER=""
+done
+printf "%s\n" "- Pairing with $PH_MOON_SRV"
+moonlight pair "$PH_MOON_SRV"
+unset PH_OPTAR
+return 0
+}
+
 function ph_open_shell_session {
 
 clear
@@ -117,69 +178,6 @@ function ph_configure_kodi {
 
 printf "%s\n" "- Configuring Kodi"
 printf "%2s%s\n" "" "SUCCESS : Nothing to configure"
-return 0
-}
-
-function ph_configure_moon {
-
-typeset PH_i=""
-typeset PH_ANSWER=""
-typeset PH_APP="Moonlight"
-typeset -i PH_COUNT=0
-
-for PH_i in PH_MOON_RES PH_MOON_FPS PH_MOON_BITRATE PH_MOON_PCKTSIZE PH_MOON_USE_CTRL PH_MOON_NUM_CTRL PH_MOON_CMD_OPTS PH_MOON_GAME PH_MOON_SRV
-do
-	PH_COUNT=0
-	confopts_ph.sh -p get -a Moonlight -o "$PH_i" | tail -n +3
-	confopts_ph.sh -p help -a Moonlight -o "$PH_i" | tail -n +3
-	printf "%s\n" "- Prompting for requested change"
-	while [[ $PH_ANSWER != @(y|n) ]]
-	do
-		[[ $PH_COUNT -gt 0 ]] && printf "\n%10s%s\n\n" "" "ERROR : Invalid response"
-		printf "%8s%s" "" "--> Do you want the change the value for $PH_i (y/n) ? "
-		[[ "$PH_i" == "PH_MOON_SRV" ]] && (printf "\n\n%12s%s\n" "" "- A value for PH_MOON_SRV is required for further configuration" ; \
-				printf "%12s%s" "" "- An empty value for PH_MOON_SRV will end configuration but it can later be restarted using either 'confapps_ph.sh' or the PieHelper menu : ")
-		read PH_ANSWER 2>/dev/null
-		ph_screen_input $PH_ANSWER || return $?
-		((PH_COUNT++))
-	done
-	printf "%10s%s\n" "" "OK"
-	if [[ "$PH_ANSWER" == "y" ]]
-	then
-		false
-		while [[ $? -ne 0 ]]
-		do
-			[[ "$PH_ANSWER" != "y" ]] && printf "%s\n" "- Prompting for requested change"
-			PH_ANSWER=""
-			while [[ "$PH_ANSWER" == "" ]]
-			do
-				printf "%8s%s" "" "--> Please enter the new value for $PH_i : "
-				read PH_ANSWER 2>/dev/null
-				[[ "$PH_i" == "PH_MOON_GAME" ]] && break
-			done
-			printf "%10s%s\n" "" "OK"
-			printf "%2s%s\n" "" "SUCCESS"
-			set -o pipefail
-			confopts_ph.sh -p set -a Moonlight -o "$PH_i"="$PH_ANSWER" -m | tail -n +3
-		done
-		set +o pipefail
-	else
-		printf "%2s%s\n" "" "SUCCESS"
-## temporary fix for PH_MOON_SRV
-		. $PH_CONF_DIR/Moonlight.conf >/dev/null 2>&1
-## end temp fix
-		[[ "$PH_i" == "PH_MOON_SRV" && -z "$PH_MOON_SRV" ]] && return 0
-	fi
-	PH_ANSWER=""
-done
-printf "%s\n" "- Pairing with $PH_MOON_SRV"
-if moonlight pair $PH_MOON_SRV 2>&1 | nawk '{ printf "%2s%s\n", "", $0 }'
-then
-	printf "%2s%s\n" "" "SUCCESS"
-else
-	printf "%2s%s\n" "" "FAILED"
-	return 1
-fi
 return 0
 }
 
@@ -1179,7 +1177,7 @@ printf "\n"
 printf "%8s%s\n\n" "" "Emulationstation ROMS can either :"
 printf "%10s%s\n" "" "- be copied locally under $PH_EMUL_SETUP_DIR/roms"
 printf "%10s%s\n" "" "- OR be provided over CIFS by setting the appropriate options for Emulationstation"
-printf "%12s%s\n" "" "using either confopts_ph.sh or the PieHelper menu"
+printf "%12s%s\n" "" "using either 'confopts_ph.sh' or the PieHelper menu"
 printf "\n"
 ph_print_bannerline
 printf "\n"
