changes for CLI tools

diff --git a/files/MovefromPieHScript.template b/files/MovefromPieHScript.template
--- a/files/MovefromPieHScript.template
+++ b/files/MovefromPieHScript.template
@@ -1,29 +1,32 @@
 #!/bin/ksh
-# Move from Kodi to Emulationstation (by Davy Keppens on 04/10/2018)
-# Enable/Disable debug by running confpieh_ph.sh -d koditoemul.sh
+# Move from PieHelper to #PH_APP# (by Davy Keppens on 04/10/2018)
+# Enable/Disable debug by running confpieh_ph.sh -d piehto#PH_APPL#.sh
 
 . $(dirname $0)/../main/main.sh || exit $? && set +x
 
 #set -x
 
-typeset PH_RUNAPP="Emulationstation"
-typeset PH_STOPAPP="Kodi"
+typeset PH_RUNAPP="#PH_APP#"
+typeset PH_STOPAPP="PieHelper"
 typeset PH_OPTION=""
+typeset PH_FLAG=""
 typeset PH_OLDOPTARG="$OPTARG"
 typeset -i PH_OLDOPTIND=$OPTIND
 typeset -l PH_RUNAPPL=`echo $PH_RUNAPP | cut -c1-4`
 typeset -l PH_STOPAPPL=`echo $PH_STOPAPP | cut -c1-4`
 OPTIND=1
 
-while getopts h PH_OPTION 2>/dev/null
+while getopts hp PH_OPTION 2>/dev/null
 do
-        case $PH_OPTION in *)
-                >&2 printf "%s%s%s%s\n" "Usage : $PH_STOPAPPL" "to" "$PH_RUNAPPL" ".sh | -h"
+        case $PH_OPTION in p)
+                PH_FLAG="pseudo" ;;
+                           *)
+                >&2 printf "%s%s%s%s\n" "Usage : $PH_STOPAPPL" "to" "$PH_RUNAPPL" ".sh '-p' | -h"
                 >&2 printf "\n"
                 >&2 printf "%3s%s\n" "" "Where -h displays this usage"
                 >&2 printf "%9s%s\n" "" "- Running this script without parameters will stop an instance of $PH_STOPAPP running on it's allocated TTY if"
-		>&2 printf "%9s%s\n" ""	"  the currently active TTY is the TTY allocated to $PH_STOPAPP"
-		>&2 printf "%9s%s\n" "" "  If successful, a new instance of $PH_RUNAPP will be started on it's allocated TTY"
+                >&2 printf "%9s%s\n" "" "  the currently active TTY is the TTY allocated to $PH_STOPAPP"
+                >&2 printf "%9s%s\n" "" "  If successful, a new instance of $PH_RUNAPP will be started on it's allocated TTY"
                 >&2 printf "%12s%s\n" "" "- The first unallocated TTY will be automatically assigned to any application without a TTY that attempts to start"
                 >&2 printf "%12s%s\n" "" "- A TTY is only deallocated when an application is removed from PieHelper"
                 >&2 printf "%12s%s\n" "" "- If an application in need of a TTY attempts to start but all TTY's are already allocated, startup will fail"
@@ -35,11 +38,17 @@ do
 		>&2 printf "%15s%s\n" "" "  A move script is defined as a script named 'xxxx'to'yyyy'.sh where 'xxxx' is the shortname of the application it will stop"
 		>&2 printf "%15s%s\n" "" "  and 'yyyy' is the shortname of the application it will start"
                 >&2 printf "%12s%s\n" "" "- Additionally, the following rules apply to the stop of $PH_STOPAPP :"
+                >&2 printf "%15s%s\n" "" "- If a $PH_STOPAPP instance is running on a pseudo-terminal, stop will fail"
                 >&2 printf "%15s%s\n" "" "- If no active instance of $PH_STOPAPP can be found on it's allocated TTY or"
                 >&2 printf "%15s%s\n" "" "  the TTY for $PH_STOPAPP cannot be determined, stop will be skipped but succeed with a warning"
                 >&2 printf "%12s%s\n" "" "- Additionally, the following rules apply to the start of $PH_RUNAPP :"
-		>&2 printf "%15s%s\n" "" "- If a persistent $PH_RUNAPP instance is already running on that TTY, that TTY will become the active TTY"
+                >&2 printf "%15s%s\n" "" "- If a persistent $PH_RUNAPP instance is already running on that TTY, that TTY will become the active TTY"
                 >&2 printf "%15s%s\n" "" "- If a non-persistent $PH_RUNAPP instance is already running on that TTY, startup will fail"
+                >&2 printf "%9s%s\n" "" "-p allows setting the stop of $PH_STOPAPP to be executed on a pseudo-terminal instead of it's allocated TTY"
+                >&2 printf "%12s%s\n" "" "- Specifying -p is optional"
+                >&2 printf "%12s%s\n" "" "- The following rules replace these for a normal stop :"
+                >&2 printf "%15s%s\n" "" "- If a $PH_STOPAPP instance is running on it's allocated TTY, stop will fail"
+                >&2 printf "%15s%s\n" "" "- If no active instance of $PH_STOPAPP can be found on a pseudo-terminal, stop will be skipped but succeed with a warning"
                 >&2 printf "\n"
                 OPTIND=$PH_OLDOPTIND ; OPTARG="$PH_OLDOPTARG" ; exit 1 ;;
         esac
@@ -47,12 +56,17 @@ done
 OPTIND=$PH_OLDOPTIND
 OPTARG="$PH_OLDOPTARG"
 
-if [[ `fgconsole` -ne `ph_get_tty_for_app $PH_STOPAPP` ]]
+if [[ `fgconsole` -ne `ph_get_tty_for_app $PH_STOPAPP` && "$PH_FLAG" != "pseudo" ]]
 then
-	printf "%s\n" "- Disabling $PH_STOPAPP"
-	printf "%2s%s\n" "" "FAILED : $PH_STOPAPP not currently on foreground"
-	exit 1
+        printf "%s\n" "- Disabling $PH_STOPAPP"
+        printf "%2s%s\n" "" "FAILED : $PH_STOPAPP not currently on foreground"
+        exit 1
 fi
-stop"$PH_STOPAPPL".sh || exit $?
+if [[ -z "$PH_FLAG" ]]
+then
+	stop"$PH_STOPAPPL".sh || exit $?
+else
+	stop"$PH_STOPAPPL".sh -p || exit $?
+fi
 start"$PH_RUNAPPL".sh || exit $?
 exit 0
