Global fixes for ph_configure_pieh action

diff --git a/files/StartScript.template b/files/StartScript.template
--- a/files/StartScript.template
+++ b/files/StartScript.template
@@ -1,134 +1,175 @@
-#!/bin/ksh
-# Start #PH_APP# (by Davy Keppens on 04/10/2018)
+#!/bin/bash
+# Run '#PH_APP#' start action (by Davy Keppens on 04/10/2018)
 # Enable/Disable debug by running 'confpieh_ph.sh -p debug -m start#PH_APPL#.sh'
 
-. $(dirname "$0")/../main/main.sh || exit "$?" && set +x
+. "$(dirname "$0")"/../main/main.sh || exit "$?" && set +x
 
 #set -x
 
-typeset PH_RUNAPP="#PH_APP#"
-typeset PH_RUNAPP_CMD=""
-typeset PH_EXCEPTION=""
-typeset PH_OPTION=""
-typeset PH_OLDOPTARG="$OPTARG"
-typeset PH_i=""
-typeset -l PH_APPSL=""
-typeset -l PH_RUNAPPL=`echo "$PH_RUNAPP" | cut -c1-4`
-typeset -u PH_RUNAPPU=`echo "$PH_RUNAPP" | cut -c1-4`
-typeset -i PH_RUNAPP_TTY=0
-typeset -i PH_OLDOPTIND="$OPTIND"
+declare PH_RUNAPP="#PH_APP#"
+declare PH_RUNAPP_STATE=""
+declare PH_EXCEPTION=""
+declare PH_OPTION=""
+declare PH_i=""
+declare PH_STOPAPPS="None"
+declare PH_OLDOPTARG="$OPTARG"
+declare -i PH_OLDOPTIND="$OPTIND"
+declare -i PH_RUNAPP_TTY="0"
+declare -i PH_PIEH_TTY="0"
+declare -i PH_FG_CONSOLE="0"
+declare -l PH_RUNAPPL="${PH_RUNAPP:0:4}"
+declare -u PH_RUNAPPU="${PH_RUNAPP:0:4}"
+
 OPTIND="1"
 
 while getopts h PH_OPTION 2>/dev/null
 do
         case "$PH_OPTION" in *)
-                >&2 printf "%s%s%s\n" "Usage : start" "$PH_RUNAPPL" ".sh | -h"
+                >&2 printf "\n\033[36m%s%s%s\033[0m\n" "Usage : start" "$PH_RUNAPPL" ".sh | -h"
                 >&2 printf "\n"
                 >&2 printf "%3s%s\n" "" "Where -h displays this usage"
-                >&2 printf "%9s%s\n" "" "- Running this script without parameters will start a new instance of '$PH_RUNAPP' on it's allocated TTY"
+                >&2 printf "%9s%s\n" "" "- Running this script without parameters will start a new instance of '$PH_RUNAPP' on it's allocated TTY and that TTY will become the active TTY"
                 >&2 printf "%12s%s\n" "" "- The first unallocated TTY will be automatically assigned to any application without a TTY that attempts to start"
                 >&2 printf "%12s%s\n" "" "- A TTY is only deallocated when an application is removed from PieHelper"
                 >&2 printf "%12s%s\n" "" "- If an application in need of a TTY attempts to start but all TTY's are already allocated, startup will fail"
-                >&2 printf "%12s%s\n" "" "- At any application start, all other running applications marked non-persistent, will first be stopped"
+                >&2 printf "%12s%s\n" "" "- At any application start, all other running integrated applications will first be stopped"
                 >&2 printf "%12s%s\n" "" "  Two exceptions to this rule exist :"
                 >&2 printf "%15s%s\n" "" "- PieHelper starting on a pseudo-terminal will never stop running applications"
-                >&2 printf "%15s%s\n" "" "- To avoid unnecessary actions for move scripts, stop actions performed directly by those will not be repeated"
-                >&2 printf "%15s%s\n" "" "  A move script is defined as a script named 'xxxx'to'yyyy'.sh where 'xxxx' is the shortname of the application it will stop"
-                >&2 printf "%15s%s\n" "" "  and 'yyyy' is the shortname of the application it will start"
+                >&2 printf "%15s%s\n" "" "- Applications marked as persistent remain online" 
                 >&2 printf "%12s%s\n" "" "- Additionally, the following rules apply to the start of '$PH_RUNAPP' :"
+                >&2 printf "%15s%s\n" "" "- '$PH_RUNAPP' must be an integrated application or startup will fail"
                 >&2 printf "%15s%s\n" "" "- If a persistent '$PH_RUNAPP' instance is already running on that TTY, that TTY will become the active TTY"
                 >&2 printf "%15s%s\n" "" "- If a non-persistent '$PH_RUNAPP' instance is already running on that TTY, startup will fail"
                 >&2 printf "\n"
-                OPTIND="$PH_OLDOPTIND" ; OPTARG="$PH_OLDOPTARG" ; exit 1 ;;
+                OPTIND="$PH_OLDOPTIND"
+		OPTARG="$PH_OLDOPTARG"
+		exit 1 ;;
         esac
 done
 OPTIND="$PH_OLDOPTIND"
 OPTARG="$PH_OLDOPTARG"
 
-if [[ `"$PH_SUDO" cat /proc/"$PPID"/comm` != restart*sh ]]
+printf "\n\033[36m%s\033[0m\n\n" "- Executing '$PH_RUNAPP' start action prechecks"
+PH_PIEH_TTY="$(ph_get_app_tty_from_app_name PieHelper)"
+PH_RUNAPP_STATE="$(ph_get_app_state_from_app_name "$PH_RUNAPP")"
+PH_FG_CONSOLE="$("$PH_SUDO" fgconsole 2>/dev/null)"
+if [[ "$("$PH_SUDO" cat "/proc/$PPID/comm")" != restart*sh ]]
 then
-        ph_check_app_name -i -a "$PH_RUNAPP" || exit "$?"
-fi
-printf "\033[36m%s\033[0m\n" "- Checking for application presences"
-[[ `"$PH_SUDO" cat /proc/"$PPID"/comm` == +(?)to+(?).sh ]] && PH_EXCEPTION=`nawk '$1 ~ /^stop.*\.sh$/ { print substr($1,5,length($1)-7) }' "$PH_SCRIPTS_DIR"/\`"$PH_SUDO" cat /proc/"$PPID"/comm\``
-for PH_i in `cut -f1 "$PH_CONF_DIR"/installed_apps | egrep -v ^"$PH_RUNAPP"$ | paste -d" " -s`
-do
-	PH_RUNAPPL=`echo "$PH_i" | cut -c1-4`
-	if [[ "$PH_EXCEPTION" != "$PH_RUNAPPL" ]]
+	printf "%8s%s\n" "" "--> Checking for '$PH_RUNAPP' integration"
+	if [[ "$PH_RUNAPP_STATE" == @(Integrated|Halted|Running) ]]
 	then
-		printf "%8s%s\n" "" "--> Checking for '$PH_i'"
-		PH_RUNAPP_TTY=`ph_get_tty_for_app "$PH_i"`
-		PH_RUNAPP_CMD=`nawk -v runapp=^"$PH_i"$ 'BEGIN { ORS=" " } $1 ~ runapp { for (i=2;i<=NF;i++) { if (i==NF) { ORS="" ; print $i } else { print $i }}}' "$PH_CONF_DIR"/supported_apps`
-		PH_RUNAPP_CMD=`sed "s/PH_TTY/$PH_RUNAPP_TTY/" <<<"$PH_RUNAPP_CMD"`
-		[[ "$PH_i" == "Bash" ]] && PH_RUNAPP_CMD="bash"
-		if pgrep -t tty"$PH_RUNAPP_TTY" -f "$PH_RUNAPP_CMD" >/dev/null
+		ph_set_result -r "$?"
+		printf "%10s\033[32m%s\033[0m\n" "" "OK ('$PH_RUNAPP_STATE')"
+	else
+		ph_set_result -r "$?" -m "Integration is mandatory for '$PH_RUNAPP' start"
+		printf "%10s\033[31m%s\033[0m\n" "" "ERROR : Invalid application state"
+		ph_show_result
+		exit "$?"
+	fi
+fi
+printf "%8s%s\n" "" "--> Checking for running applications"
+if [[ "$("$PH_SUDO" cat "/proc/$PPID/comm" 2>/dev/null)" == +(?)to+(?).sh ]]
+then
+	PH_EXCEPTION="$(nawk '$1 ~ /^stop.*\.sh$/ { print substr($1,5,length($1)-7) }' "$PH_SCRIPTS_DIR/$("$PH_SUDO" cat "/proc/$PPID/comm")" 2>/dev/null)"
+fi
+for PH_i in $(confapps_ph.sh -p list -k run 2>/dev/null | grep -v Skipping | tail -n +4 | tac | tail -n +4 | nawk -v runappl=^"$PH_RUNAPPL"$ -v except=^"$PH_EXCEPTION"$ 'BEGIN { FS = "\x27" ; ORS = " " }
+											$2 !~ /^None$/ && tolower(substr($2,1,4)) !~ except && tolower(substr($2,1,4)) !~ runappl { print $2 }')
+do
+	if [[ "$PH_STOPAPPS" != "None" ]]
+	then
+		PH_STOPAPPS="$PH_STOPAPPS $PH_i"
+	else
+		PH_STOPAPPS="$PH_i"
+	fi
+done
+ph_set_result -r 0
+if [[ "$PH_STOPAPPS" == "None" ]]
+then
+	printf "%10s\033[32m%s\033[0m\n" "" "OK ('$PH_STOPAPPS')"
+	PH_STOPAPPS=""
+else
+	printf "%10s\033[33m%s\033[0m\n" "" "Warning : The following applications are running ('$PH_STOPPAPPS') -> Stopping"
+fi
+for PH_i in $(echo -n "$PH_STOPAPPS")
+do
+	if ! ph_do_app_action stop "$PH_i"
+	then
+		ph_show_result
+		exit "$?"
+	else
+		[[ "$(ph_get_app_state_from_app_name "$PH_i")" == "Running" ]] && PH_STOPAPPS="$(sed "s/^$PH_i //g;s/ $PH_i / /g;s/ $PH_i$//g" <<<"$PH_STOPAPPS" 2>/dev/null)"
+	fi
+done
+[[ -z "$PH_STOPAPPS" ]] && PH_STOPAPPS="None"
+ph_set_result -m "The following applications were stopped ('$PH_STOPAPPS')"
+ph_get_app_tty "$PH_RUNAPP"
+PH_RUNAPP_TTY="$?"
+if [[ "$PH_RUNAPP_TTY" -le "1" || "$PH_RUNAPP_TTY" -gt "$PH_PIEH_MAX_TTYS" ]]
+then
+	ph_set_result -m "A valid TTY allocation is mandatory for '$PH_RUNAPP' start"
+	ph_show_result -t
+	exit "$?"
+fi
+printf "%8s%s\n" "" "--> Checking for '$PH_RUNAPP' presence"
+if [[ "$PH_RUNAPP_STATE" != "Running" ]]
+then
+	printf "%10s\033[32m%s\033[0m\n" "" "OK (Not found) -> Starting"
+	ph_set_result -r 0
+	ph_show_result
+	ph_set_result -t -r "$?"
+	printf "\033[36m%s\033[0m\n\n" "- Executing '$PH_RUNAPP' start action"
+	"$PH_SUDO" rm "$PH_TMP_DIR/Start.report" 2>/dev/null
+	set -o pipefail
+	if ph_do_app_action start "$PH_RUNAPP" | tee -a "$PH_TMP_DIR/Start.report" 2>/dev/null
+	then
+		set +o pipefail
+		[[ "$PH_RUNAPP" == "Bash" ]] && exit 0
+	else
+		set +o pipefail
+		if [[ "$PH_FG_CONSOLE" -ne "$PH_RUNAPP_TTY" ]]
 		then
-			printf "%10s%s\n" "" "Warning : '$PH_i' is active -> Stopping"
-			[[ -n "$PH_APPSL" ]] && PH_APPSL="$PH_APPSL $PH_RUNAPPL" || PH_APPSL="$PH_RUNAPPL"
+			ph_show_result
+			ph_set_result -t -r "$?"
+			printf "\033[36m%s\033[0m\n\n" "- Displaying 'FAILED' status report for '$PH_RUNAPP' start"
+			if cat "$PH_TMP_DIR/Start.report" 2>/dev/null
+			then
+				ph_set_result -r 0
+			else
+				ph_set_result -r 1 -m "An error occurred displaying status report '$PH_TMP_DIR/Start.report' of '$PH_RUNAPP' start"
+			fi
 		else
-			[[ "$PH_i" == "PieHelper" ]] && printf "%10s\033[32m%s\033[0m\n" "" "OK (Not found or running on a pseudo-terminal)" || \
-								printf "%10s\033[32m%s\033[0m\n" "" "OK (Not found)"
+			"$PH_SUDO" rm "$PH_TMP_DIR/Start.report" 2>/dev/null
+			ph_show_result
+			ph_set_result -t -r "$?"
+			ph_show_result -t
+			if [[ "$PH_PIEH_TTY" -gt "1" && "$PH_PIEH_TTY" -le "$PH_PIEH_MAX_TTYS" ]]
+			then
+				"$PH_SUDO" chvt "$PH_PIEH_TTY" 2>/dev/null
+			else
+				"$PH_SUDO" chvt 1 2>/dev/null
+			fi
+			"$PH_SUDO" systemctl stop "getty@tty$PH_RUNAPP_TTY" >/dev/null 2>&1
+			"$PH_SUDO" systemctl daemon-reload >/dev/null 2>&1
+			exit 1
 		fi
 	fi
-done
-printf "%2s\033[32m%s\033[0m\n\n" "" "SUCCESS"
-for PH_i in `echo -n "$PH_APPSL"`
-do
-	"$PH_SCRIPTS_DIR"/stop"$PH_i".sh || exit "$?"
-done
-printf "\033[36m%s\033[0m\n" "- Enabling '$PH_RUNAPP'"
-PH_RUNAPPL=`echo "$PH_RUNAPP" | cut -c1-4 2>/dev/null`
-PH_RUNAPPU=`echo "$PH_RUNAPP" | cut -c1-4 2>/dev/null`
-printf "%8s%s\n" "" "--> Attempting to determine TTY for '$PH_RUNAPP'"
-PH_RUNAPP_TTY=`ph_get_tty_for_app "$PH_RUNAPP"`
-if [[ "$?" -eq 0 ]]
-then
-	printf "%10s\033[32m%s\033[0m\n" "" "OK"
-	ph_setup_tty "$PH_RUNAPP_TTY" "$PH_RUNAPP"
+	"$PH_SUDO" rm "$PH_TMP_DIR/Start.report" 2>/dev/null
+	ph_show_result
+	ph_set_result -t -r "$?"
 else
-	if [[ "$PH_RUNAPP_TTY" -eq 0 ]]
+	if [[ "$(eval "echo -n \$PH_""$PH_RUNAPPU""_PERSISTENT")" == "no" ]]
 	then
-		printf "%10s\033[31m%s\033[0m\n" "" "ERROR : All TTY's already allocated"
-		printf "%2s\033[31m%s\033[0m\n\n" "" "FAILED"
-		exit 1
+		printf "%10s\033[31m%s\033[0m\n\n" "" "ERROR : Found"
+		ph_set_result -r 1 -m "An error occurred starting '$PH_RUNAPP' on 'TTY$PH_RUNAPP_TTY' (Already non-persistently running)"
+		ph_show_result
 	else
-		printf "%10s\033[32m%s\033[0m\n" "" "OK"
+		printf "%10s\033[33m%s\033[0m\n\n" "" "Warning : Found"
+		ph_set_result -r 0 -w -m "'$PH_RUNAPP' already persistently running on 'TTY$PH_RUNAPP_TTY' -> Switching to instance"
+		ph_show_result
+		sleep 2 2>/dev/null
+		"$PH_SUDO" chvt "$PH_RUNAPP_TTY" 2>/dev/null
 	fi
+	exit "$?"
 fi
-PH_RUNAPP_CMD=`nawk -v runapp=^"$PH_RUNAPP"$ 'BEGIN { ORS=" " } $1 ~ runapp { for (i=2;i<=NF;i++) { if (i==NF) { ORS="" ; print $i } else { print $i }}}' "$PH_CONF_DIR"/supported_apps 2>/dev/null`
-PH_RUNAPP_CMD=`sed "s/PH_TTY/$PH_RUNAPP_TTY/" <<<"$PH_RUNAPP_CMD"`
-printf "%8s%s\n" "" "--> Checking for '$PH_RUNAPP'"
-[[ "$PH_RUNAPP" == "Bash" ]] && PH_RUNAPP_CMD="bash"
-if pgrep -t tty"$PH_RUNAPP_TTY" -f "$PH_RUNAPP_CMD" >/dev/null
-then
-	if [[ "$PH_RUNAPP" == "Bash" ]]
-	then
-		if [[ -n `ps --ppid \`pgrep -t tty"$PH_RUNAPP_TTY" -f "$PH_RUNAPP_CMD"\` 2>/dev/null | tail -n +2` ]]
-		then
-			printf "%10s\033[32m%s\033[0m\n" "" "OK (Not found)"
-			ph_run_app_action start "$PH_RUNAPP" || (printf "%2s\033[31m%s\033[0m\n\n" "" "FAILED" ; return 1) || exit "$?"
-			exit 0
-		fi
-	fi
-	if [[ `eval echo "\\$PH_\$PH_RUNAPPU"_PERSISTENT` == "no" ]]
-	then
-		printf "%10s\033[31m%s\033[0m\n" "" "ERROR : '$PH_RUNAPP' already running on 'TTY$PH_RUNAPP_TTY'"
-		printf "%2s\033[31m%s\033[0m\n\n" "" "FAILED"
-		exit 1
-	else
-		printf "%10s%s\n" "" "Warning : '$PH_RUNAPP' already persistent on 'TTY$PH_RUNAPP_TTY'"
-		printf "%2s\033[32m%s\033[0m\n\n" "" "SUCCESS"
-		"$PH_SUDO" chvt "$PH_RUNAPP_TTY"
-	fi
-else
-	printf "%10s\033[32m%s\033[0m\n" "" "OK (Not found)"
-	ph_run_app_action start "$PH_RUNAPP"
-	if [[ "$?" -eq 0 ]]
-	then
-		[[ "$PH_RUNAPP" != "Bash" ]] && printf "%2s\033[32m%s\033[0m\n\n" "" "SUCCESS"
-	else
-		printf "%2s\033[31m%s\033[0m\n\n" "" "FAILED"
-		exit 1
-	fi
-fi
-exit 0
+ph_show_result -t
+exit "$?"
diff --git a/files/StopScript.template b/files/StopScript.template
--- a/files/StopScript.template
+++ b/files/StopScript.template
@@ -1,25 +1,30 @@
-#!/bin/ksh
-# Stop #PH_APP# (by Davy Keppens on 04/10/2018)
+#!/bin/bash
+# Run '#PH_APP#' stop action (by Davy Keppens on 04/10/2018)
 # Enable/Disable debug by running 'confpieh_ph.sh -p debug -m stop#PH_APPL#.sh'
 
-. $(dirname "$0")/../main/main.sh || exit "$?" && set +x
+. "$(dirname "$0")"/../main/main.sh || exit "$?" && set +x
 
 #set -x
 
-typeset PH_STOPAPP="#PH_APP#"
-typeset PH_PARAM="$1"
-typeset PH_OPTION=""
-typeset PH_STOPAPP_CMD=""
-typeset PH_OLDOPTARG="$OPTARG"
-typeset -l PH_STOPAPPL=`echo "$PH_STOPAPP" | cut -c1-4`
-typeset -i PH_STOPAPP_TTY="0"
-typeset -i PH_OLDOPTIND="$OPTIND"
+declare PH_STOPAPP="#PH_APP#"
+declare PH_STOPAPP_STATE=""
+declare PH_PARAM=""
+declare PH_OPTION=""
+declare PH_OLDOPTARG="$OPTARG"
+declare -i PH_OLDOPTIND="$OPTIND"
+declare -i PH_STOPAPP_TTY="0"
+declare -l PH_STOPAPPL="${PH_STOPAPP:0:4}"
+
 OPTIND="1"
 
-while getopts h PH_OPTION 2>/dev/null
+while getopts fh PH_OPTION 2>/dev/null
 do
-        case "$PH_OPTION" in *)
-                >&2 printf "%s%s%s\n" "Usage : stop" "$PH_STOPAPPL" ".sh | -h"
+        case "$PH_OPTION" in f)
+		[[ -n "$PH_PARAM" ]] && (! "stop$PH_STOPAPPL.sh" -h) && OPTIND="$PH_OLDOPTIND" && \
+			OPTARG="$PH_OLDOPTARG" && exit 1
+		PH_PARAM="force" ;;
+			     *)
+                >&2 printf "\n\033[36m%s%s%s\033[0m\n" "Usage : stop" "$PH_STOPAPPL" ".sh | -h"
                 >&2 printf "\n"
                 >&2 printf "%3s%s\n" "" "Where -h displays this usage"
                 >&2 printf "%9s%s\n" "" "- Running this script without parameters will stop an instance of '$PH_STOPAPP' running on it's allocated TTY"
@@ -28,41 +33,57 @@ do
                 >&2 printf "%15s%s\n" "" "- If no active instance of '$PH_STOPAPP' can be found on it's allocated TTY or"
                 >&2 printf "%15s%s\n" "" "  the TTY for '$PH_STOPAPP' cannot be determined, stop will be skipped but succeed with a warning"
                 >&2 printf "\n"
-                OPTIND="$PH_OLDOPTIND" ; OPTARG="$PH_OLDOPTARG" ; exit 1 ;;
+                OPTIND="$PH_OLDOPTIND"
+		OPTARG="$PH_OLDOPTARG"
+		exit 1 ;;
         esac
 done
 OPTIND="$PH_OLDOPTIND"
 OPTARG="$PH_OLDOPTARG"
 
-if [[ `"$PH_SUDO" cat /proc/"$PPID"/comm 2>/dev/null` != "confsupp_ph.sh" ]]
+printf "\n\033[36m%s\033[0m\n\n" "- Executing '$PH_STOPAPP' stop action prechecks"
+PH_STOPAPP_STATE="$(ph_get_app_state_from_app_name "$PH_STOPAPP")"
+printf "%8s%s\n" "" "--> Checking for '$PH_STOPAPP' integration"
+if [[ "$PH_STOPAPP_STATE" == @(Integrated|Halted|Running) ]]
 then
-        ph_check_app_name -i -a "$PH_STOPAPP" || exit "$?"
-fi
-printf "\033[36m%s\033[0m\n" "- Disabling '$PH_STOPAPP'"
-printf "%8s%s\n" "" "--> Attempting to determine TTY for '$PH_STOPAPP'"
-PH_STOPAPP_TTY=`ph_get_tty_for_app "$PH_STOPAPP"`
-[[ "$?" -eq 1 && "$PH_STOPAPP_TTY" -ne 0 ]] && printf "%10s\033[32m%s\033[0m\n" "" "OK ('TTY$PH_STOPAPP_TTY')" || \
-		(printf "%10s%s\n" "" "Warning : Could not determine TTY for '$PH_STOPAPP'" ; printf "%2s\033[32m%s\033[0m\n\n" "" "SUCCESS" ; return 1) || \
-		 exit 0
-PH_STOPAPP_CMD=`nawk -v runapp=^"$PH_STOPAPP"$ 'BEGIN { ORS=" " } $1 ~ runapp { for (i=2;i<=NF;i++) { if (i==NF) { ORS="" ; print $i } else { print $i }}}' "$PH_CONF_DIR"/supported_apps 2>/dev/null`
-PH_STOPAPP_CMD=`sed "s/PH_TTY/$PH_STOPAPP_TTY/" <<<"$PH_STOPAPP_CMD"`
-printf "%8s%s\n" "" "--> Checking for '$PH_STOPAPP'"
-[[ "$PH_STOPAPP" == "Bash" ]] && PH_STOPAPP_CMD="bash"
-if pgrep -t tty"$PH_STOPAPP_TTY" -f "$PH_STOPAPP_CMD"  >/dev/null 2>&1
-then
-	printf "%10s\033[32m%s\033[0m\n" "" "OK (Found)"
-        [[ -z "$1" && `"$PH_SUDO" cat /proc/"$PPID"/comm` != @(start*sh|+(?)to+(?).sh|restart!("$PH_STOPAPPL").sh) ]] && \
-			PH_PARAM="force"
-	ph_run_app_action stop "$PH_STOPAPP" "$PH_PARAM"
-	case "$?" in 3)
-		printf "%2s\033[31m%s\033[0m\n\n" "" "PARTIALLY FAILED"
-		exit 1 ;;
-		     1)
-		printf "%2s\033[31m%s\033[0m\n\n" "" "FAILED"
-		exit 1 ;;
-	esac
+	ph_set_result -r "$?"
+	printf "%10s\033[32m%s\033[0m\n" "" "OK ('$PH_STOPAPP_STATE')"
 else
-	printf "%10s%s\n" "" "Warning : '$PH_STOPAPP' not running"
+	ph_set_result -r "$?" -m "Integration is mandatory for '$PH_STOPAPP' stop"
+	printf "%10s\033[31m%s\033[0m\n" "" "ERROR : Invalid application state"
+	ph_show_result
+	exit "$?"
 fi
-printf "%2s\033[32m%s\033[0m\n\n" "" "SUCCESS"
-exit 0
+printf "%8s%s\n" "" "--> Determining '$PH_STOPAPP' TTY"
+PH_STOPAPP_TTY="$(ph_get_app_tty_from_app_name "$PH_STOPAPP")"
+if [[ "$PH_STOPAPP_TTY" -le "1" || "$PH_STOPAPP_TTY" -gt "$PH_PIEH_MAX_TTYS" ]]
+then
+	printf "%10s\033[33m%s\033[0m\n" "" "Warning : Could not determine TTY"
+	ph_set_result -r 0 -w -m "A valid TTY allocation is mandatory for '$PH_STOPAPP' stop"
+	ph_show_result
+	exit "$?"
+else
+	printf "%10s\033[32m%s\033[0m\n" "" "OK ('TTY$PH_STOPAPP_TTY')"
+	ph_set_result -r 0
+fi
+printf "%8s%s\n" "" "--> Checking for '$PH_STOPAPP' presence"
+if [[ "$PH_STOPAPP_STATE" == "Running" ]]
+then
+	printf "%10s\033[32m%s\033[0m\n\n" "" "OK (Found) -> Stopping"
+	ph_set_result -r 0
+	ph_show_result
+	ph_set_result -t -r "$?"
+	printf "\033[36m%s\033[0m\n\n" "- Executing '$PH_STOPAPP' stop action"
+        [[ -z "$1" && "$("$PH_SUDO" cat "/proc/$PPID/comm")" != @(start*sh|+(?)to+(?).sh|restart!("$PH_STOPAPPL").sh) ]] && \
+			PH_PARAM="force"
+	ph_do_app_action stop "$PH_STOPAPP" $PH_PARAM
+	ph_show_result
+	ph_set_result -t -r "$?"
+else
+	printf "%10s\033[33m%s\033[0m\n\n" "" "Warning : Not found"
+	ph_set_result -r 0 -w -m "'TTY$PH_STOPAPP_TTY' allocated to '$PH_STOPAPP' already stopped"
+	ph_show_result
+	exit "$?"
+fi
+ph_show_result -t
+exit "$?"
