More changes

diff --git a/files/templates/MoveScript.template b/files/templates/MoveScript.template
--- a/files/templates/MoveScript.template
+++ b/files/templates/MoveScript.template
@@ -3,18 +3,16 @@
 # Enable/Disable debug by running 'confpieh_ph.sh -p debug -m #PH_APPL#to#PH_APPL2#.sh'
 
 . "$(dirname "${0}" 2>/dev/null)/app/main.sh" || \
-	exit "${?}" && \
+	exit 1 && \
 	set +x
 
 #set -x
 
 declare PH_RUNAPP
 declare PH_STOPAPP
-declare PH_STOPAPP_STR_TTY
 declare PH_OPTION
 declare PH_OLDOPTARG
 declare -i PH_OLDOPTIND
-declare -i PH_FG_CONSOLE
 declare -l PH_RUNAPPL
 declare -l PH_STOPAPPL
 
@@ -22,9 +20,7 @@ PH_OLDOPTARG="${OPTARG}"
 PH_OLDOPTIND="${OPTIND}"
 PH_RUNAPP="#PH_APP2#"
 PH_STOPAPP="#PH_APP#"
-PH_STOPAPP_STR_TTY=""
 PH_OPTION=""
-PH_FG_CONSOLE="0"
 PH_RUNAPPL="${PH_RUNAPP:0:4}"
 PH_STOPAPPL="${PH_STOPAPP:0:4}"
 
@@ -32,49 +28,37 @@ OPTIND="1"
 
 while getopts :h PH_OPTION
 do
-        case "${PH_OPTION}" in *)
-                >&2 printf "\n\033[1;36m%s\033[0;0m\n" "Usage : ${PH_STOPAPPL}to${PH_RUNAPPL}.sh | -h"
-                >&2 printf "\n"
-                >&2 printf "%3s\033[1;37m%s\n" "" "Where -h displays this usage"
-                >&2 printf "%9s%s\n" "" "- Running this script without parameters will stop an instance of '${PH_STOPAPP}' running on it's allocated tty if"
+	case "${PH_OPTION}" in *)
+		>&2 printf "\n\033[1;36m%s\033[0;0m\n" "Usage : ${PH_STOPAPPL}to${PH_RUNAPPL}.sh | -h"
+		>&2 printf "\n"
+		>&2 printf "%3s\033[1;37m%s\n" "" "Where -h displays this usage"
+		>&2 printf "%9s%s\n" "" "- Running this script without parameters will stop an instance of '${PH_STOPAPP}' running on its allocated tty if"
 		>&2 printf "%9s%s\n" ""	"  the currently active tty is the tty allocated to '${PH_STOPAPP}'"
-		>&2 printf "%9s%s\n" "" "  If successful, a new instance of '${PH_RUNAPP}' will be started on it's allocated tty and that tty will become the active tty"
-                >&2 printf "%12s%s\n" "" "- The first unallocated tty will be automatically assigned to any application without a tty that attempts to start"
-                >&2 printf "%12s%s\n" "" "- A tty is only deallocated when an application is removed from PieHelper"
-                >&2 printf "%12s%s\n" "" "- If an application in need of a tty attempts to start but all ttys are already allocated, startup will fail"
-                >&2 printf "%12s%s\n" "" "- Persistence will be taken into account when stopping '${PH_STOPAPP}' since the stop command is being issued indirectly"
-                >&2 printf "%12s%s\n" "" "- At any application start, all other running integrated applications will first be stopped"
-                >&2 printf "%12s%s\n" "" "  Two exceptions to this rule exist :"
-                >&2 printf "%15s%s\n" "" "- PieHelper starting on a pseudo-terminal will never stop running applications"
-                >&2 printf "%15s%s\n" "" "- Applications marked as persistent remain online"
-                >&2 printf "%12s%s\n" "" "- Additionally, the following rules apply to the stop of '${PH_STOPAPP}' :"
-                >&2 printf "%15s%s\n" "" "- If no active instance of '${PH_STOPAPP}' can be found on its allocated tty or"
-                >&2 printf "%15s%s\n" "" "  the tty for '${PH_STOPAPP}' cannot be determined, stop will be skipped but succeed with a warning"
-                >&2 printf "%12s%s\n" "" "- Additionally, the following rules apply to the start of '${PH_RUNAPP}' :"
-		>&2 printf "%15s%s\n" "" "- If a persistent '${PH_RUNAPP}' instance is already running on that tty, that tty will become the active tty"
-                >&2 printf "%15s%s\033[0;0m\n" "" "- If a non-persistent '${PH_RUNAPP}' instance is already running on that tty, startup will fail"
-                >&2 printf "\n"
-                OPTIND="${PH_OLDOPTIND}"
+		>&2 printf "%12s%s\n" "" "- If a tty is allocated to '${PH_STOPAPP}' it remains allocated"
+		>&2 printf "%15s%s\n" "" "- An applications tty is freed only when unintegrating the application"
+		>&2 printf "%12s%s\n" "" "- Persistence will be taken into account when stopping '${PH_STOPAPP}' since the stop command is issued indirectly"
+		>&2 printf "%12s%s\n" "" "- Additionally, the following rule(s) also apply to the stop of '${PH_STOPAPP}' :"
+		>&2 printf "%15s%s\n" "" "- If no active instance of '${PH_STOPAPP}' can be found on its allocated tty, stop will be skipped but succeed with a warning"
+		>&2 printf "%9s%s\n" "" "  If successful, a new instance of '${PH_RUNAPP}' will be started on its allocated tty and that tty will become the active tty"
+		>&2 printf "%12s%s\n" "" "- If '${PH_RUNAPP}' does not have a tty allocated when starting, the first unallocated tty will automatically be allocated to '${PH_RUNAPP}'"
+		>&2 printf "%15s%s\n" "" "- If an application in need of a tty attempts to start but all ttys are already allocated, startup will fail"
+		>&2 printf "%12s%s\n" "" "- At any application start, all other running integrated applications will first be stopped"
+		>&2 printf "%12s%s\n" "" "  Two exceptions to this rule exist :"
+		>&2 printf "%15s%s\n" "" "- PieHelper starting on a pseudo-terminal will never stop running applications"
+		>&2 printf "%15s%s\n" "" "- Applications marked as persistent remain online"
+		>&2 printf "%12s%s\n" "" "- Additionally, the following rule(s) also apply to the start of '${PH_RUNAPP}' :"
+		>&2 printf "%15s%s\n" "" "- If a persistent '${PH_RUNAPP}' instance is already running on its allocated tty, that tty will become the active tty"
+		>&2 printf "%15s%s\033[0;0m\n" "" "- If a non-persistent '${PH_RUNAPP}' instance is already running on its allocated tty, startup will fail"
+		>&2 printf "\n"
+		OPTIND="${PH_OLDOPTIND}"
 		OPTARG="${PH_OLDOPTARG}"
 		exit 1 ;;
-        esac
+	esac
 done
 OPTIND="${PH_OLDOPTIND}"
 OPTARG="${PH_OLDOPTARG}"
 
-printf "\n\033[1;36m%s\033[0;0m\n\n" "- Checking the requirements to stop '${PH_STOPAPP}'"
-PH_STOPAPP_STR_TTY="$(ph_get_app_tty_from_app_name "${PH_STOPAPP}")"
-PH_FG_CONSOLE="$("${PH_SUDO}" fgconsole 2>/dev/null)"
-if [[ "${PH_FG_CONSOLE}" != "${PH_STOPAPP_STR_TTY}" ]]
-then
-	ph_set_result -m "Could not stop '${PH_STOPAPP}' since the currently active tty is not allocated to '${PH_STOPAPP}'"
-	ph_run_with_rollback -c false -m "Could not stop"
-else
-	ph_run_with_rollback -c true
-	ph_set_result -t -r 0
-	ph_show_result
-	"stop${PH_STOPAPPL}.sh" || \
-		exit 1
-	"start${PH_RUNAPPL}.sh"
-fi
+"stop${PH_STOPAPPL}.sh" || \
+	exit 1
+"start${PH_RUNAPPL}.sh"
 exit "${?}"
diff --git a/files/templates/MovetoPieHScript.template b/files/templates/MovetoPieHScript.template
--- a/files/templates/MovetoPieHScript.template
+++ b/files/templates/MovetoPieHScript.template
@@ -3,20 +3,18 @@
 # Enable/Disable debug by running 'confpieh_ph.sh -p debug -m #PH_APPL#topieh.sh'
 
 . "$(dirname "${0}" 2>/dev/null)/app/main.sh" || \
-	exit "${?}" && \
+	exit 1 && \
 	set +x
 
 #set -x
 
 declare PH_RUNAPP
 declare PH_STOPAPP
-declare PH_STOPAPP_STR_TTY
 declare PH_MENU
 declare PH_MODE
 declare PH_OPTION
 declare PH_OLDOPTARG
 declare -i PH_OLDOPTIND
-declare -i PH_FG_CONSOLE
 declare -l PH_RUNAPPL
 declare -l PH_STOPAPPL
 
@@ -24,11 +22,9 @@ PH_OLDOPTARG="${OPTARG}"
 PH_OLDOPTIND="${OPTIND}"
 PH_RUNAPP="PieHelper"
 PH_STOPAPP="#PH_APP#"
-PH_STOPAPP_STR_TTY=""
 PH_MENU=""
 PH_MODE=""
 PH_OPTION=""
-PH_FG_CONSOLE="0"
 PH_RUNAPPL="${PH_RUNAPP:0:4}"
 PH_STOPAPPL="${PH_STOPAPP:0:4}"
 
@@ -36,86 +32,83 @@ OPTIND="1"
 
 while getopts :hpm: PH_OPTION
 do
-        case "${PH_OPTION}" in p)
+	case "${PH_OPTION}" in p)
 		[[ -n "${PH_MODE}" ]] && \
 			(! "${PH_STOPAPPL}topieh.sh" -h) && \
 			OPTIND="${PH_OLDOPTIND}" && \
 			OPTARG="${PH_OLDOPTARG}" && \
 			exit 1
-		PH_MODE="pseudo" ;;
+		PH_MODE="pts" ;;
 			     m)
 		[[ -n "${PH_MENU}" || "${OPTARG}" != @(Main|@(Controller|App|Setting)s|Advanced|PS@(3|4)|XBOX360|@(App|Opts|TTY)Management*) ]] && \
 			(! "${PH_STOPAPPL}topieh.sh" -h) && \
 			OPTIND="${PH_OLDOPTIND}" && \
 			OPTARG="${PH_OLDOPTARG}" && \
 			exit 1
-                PH_MENU="${OPTARG}" ;;
+		PH_MENU="${OPTARG}" ;;
 			     *)
-                >&2 printf "\n\033[1;36m%s\033[0;0m\n" "Usage : ${PH_STOPAPPL}to${PH_RUNAPPL}.sh '-p' '-m ['menu']' | -h"
-                >&2 printf "\n"
-                >&2 printf "%3s\033[1;37m%s\n" "" "Where -h displays this usage"
-                >&2 printf "%9s%s\n" "" "- Running this script without parameters will stop an instance of '${PH_STOPAPP}' running on its allocated tty if"
-                >&2 printf "%9s%s\n" "" "  the currently active tty is the tty allocated to '${PH_STOPAPP}'"
-                >&2 printf "%9s%s\n" "" "  If successful, a new instance of '${PH_RUNAPP}' will be started on its allocated tty"
-                >&2 printf "%12s%s\n" "" "- The first unallocated tty will be automatically assigned to any application without a tty that attempts to start"
-                >&2 printf "%12s%s\n" "" "- A tty is only deallocated when an application is removed from PieHelper"
-                >&2 printf "%12s%s\n" "" "- If an application in need of a tty attempts to start but all ttys are already allocated, startup will fail"
-                >&2 printf "%12s%s\n" "" "- Persistence will be taken into account when stopping '${PH_STOPAPP}' since the stop command is being issued indirectly"
-                >&2 printf "%12s%s\n" "" "- At any application start, all other running integrated applications will first be stopped"
-                >&2 printf "%12s%s\n" "" "  Two exceptions to this rule exist :"
-                >&2 printf "%15s%s\n" "" "- PieHelper starting on a pseudo-terminal will never stop running applications"
-                >&2 printf "%15s%s\n" "" "- Applications marked as persistent remain online"
-                >&2 printf "%12s%s\n" "" "- Additionally, the following rules apply to the stop of '${PH_STOPAPP}' :"
-                >&2 printf "%15s%s\n" "" "- If no active instance of '${PH_STOPAPP}' can be found on its allocated tty or"
-                >&2 printf "%15s%s\n" "" "  the tty for '${PH_STOPAPP}' cannot be determined, stop will be skipped but succeed with a warning"
-                >&2 printf "%12s%s\n" "" "- Additionally, the following rules apply to the start of '${PH_RUNAPP}' :"
-                >&2 printf "%15s%s\n" "" "- If a persistent '${PH_RUNAPP}' instance is already running on that tty, that tty will become the active tty"
-                >&2 printf "%15s%s\n" "" "- If a non-persistent '${PH_RUNAPP}' instance is already running on that tty, startup will fail"
-                >&2 printf "%15s%s\n" "" "- If a '${PH_RUNAPP}' instance is already running on a pseudo-terminal, that instance will be replaced by the new instance on its allocated tty"
-                >&2 printf "%9s%s\n" "" "-p allows setting the start of '${PH_RUNAPP}' to be executed on a pseudo-terminal instead of its allocated tty"
-                >&2 printf "%12s%s\n" "" "- Specifying -p is optional"
-                >&2 printf "%12s%s\n" "" "- The following rules replace these for a normal start :"
-                >&2 printf "%15s%s\n" "" "- If a persistent '${PH_RUNAPP}' pseudo-terminal instance is already running, startup will be skipped but succeed with a warning"
-                >&2 printf "%15s%s\n" "" "- If a non-persistent '${PH_RUNAPP}' pseudo-terminal instance is already running, startup will fail"
-                >&2 printf "%15s%s\n" "" "- If a '${PH_RUNAPP}' instance is already running on its allocated tty, that instance will be replaced by the new pseudo-terminal instance"
-                >&2 printf "%9s%s\n" "" "-m allows starting '${PH_RUNAPP}' directly in menu [menu] instead of the default 'Main' menu"
-                >&2 printf "%12s%s\n" "" "- Specifying -m is optional"
-                >&2 printf "%12s%s\n" "" "- Allowed values for [menu] are 'Main', 'Controllers', 'Apps', 'Advanced', 'Settings', 'PS3', 'PS4', 'XBOX360', 'AppManagement',"
-                >&2 printf "%12s%s\n" "" "  'OptsManagement', 'TTYManagement', 'AppManagement', the name of any supported application, as well as one of 'OptsManagement', 'AppManagement', or 'TTYManagement' concatenated with '_' and"
-                >&2 printf "%12s%s\n" "" "  the name of any supported application, f.e. 'OptsManagement_Bash', 'AppManagement_PieHelper' or 'TTYManagement_Moonlight'"
-                >&2 printf "%15s%s\n" "" "- By default, the current value of option 'PH_PIEH_CMD_OPTS' will be used"
-                >&2 printf "%18s%s\n" "" "- If PH_PIEH_CMD_OPTS has no value, it will be set to 'Main'"
-                >&2 printf "%15s%s\n" "" "- If an empty string is specified for [menu], the default will be used"
-                >&2 printf "%12s%s\033[0;0m\n" "" "- This setting will be ignored if a persistent instance of '${PH_RUNAPP}' is already active"
-                >&2 printf "\n"
-                OPTIND="${PH_OLDOPTIND}"
+		>&2 printf "\n\033[1;36m%s\033[0;0m\n" "Usage : ${PH_STOPAPPL}to${PH_RUNAPPL}.sh '-p' '-m ['menu']' | -h"
+		>&2 printf "\n"
+		>&2 printf "%3s\033[1;37m%s\n" "" "Where -h displays this usage"
+		>&2 printf "%9s%s\n" "" "- Running this script without parameters will stop an instance of '${PH_STOPAPP}' running on its allocated tty if"
+		>&2 printf "%9s%s\n" "" "  the currently active tty is the tty allocated to '${PH_STOPAPP}'"
+		>&2 printf "%12s%s\n" "" "- If '${PH_STOPAPP}' is not a supported application, stop will fail"
+		>&2 printf "%12s%s\n" "" "- If a tty is allocated to '${PH_STOPAPP}' it remains allocated"
+		>&2 printf "%15s%s\n" "" "- An applications tty is freed only when unintegrating the application"
+		>&2 printf "%12s%s\n" "" "- Persistence will be taken into account when stopping '${PH_STOPAPP}' since the stop command is issued indirectly"
+		>&2 printf "%12s%s\n" "" "- Additionally, the following rule(s) also apply when stopping '${PH_STOPAPP}' :"
+		>&2 printf "%15s%s\n" "" "- If no active instance of '${PH_STOPAPP}' can be found on its allocated tty, stop will be skipped but succeed with a warning"
+		>&2 printf "%9s%s\n" "" "  If successful, a new instance of '${PH_RUNAPP}' will be started on its allocated tty and that tty will become the active tty"
+		>&2 printf "%12s%s\n" "" "- If '${PH_RUNAPP}' is not an integrated application, startup will fail"
+		>&2 printf "%12s%s\n" "" "- If '${PH_RUNAPP}' does not have a tty allocated when starting, the first unallocated tty will automatically be allocated to '${PH_RUNAPP}'"
+		>&2 printf "%15s%s\n" "" "- If an application in need of a tty attempts to start but all ttys are already allocated, startup will fail"
+		>&2 printf "%12s%s\n" "" "- At any application start, all other running integrated applications will first be stopped"
+		>&2 printf "%12s%s\n" "" "  Two exceptions to this rule exist :"
+		>&2 printf "%15s%s\n" "" "- Applications marked as persistent remain online"
+		>&2 printf "%15s%s\n" "" "- 'PieHelper' will not stop any running applications when starting in 'pts' mode"
+		>&2 printf "%12s%s\n" "" "- 'PieHelper' will always terminate after any other application starts successfully"
+		>&2 printf "%12s%s\n" "" "- Additionally, the following rule(s) also apply when starting '${PH_RUNAPP}' in 'tty' mode :"
+		>&2 printf "%15s%s\n" "" "- If '${PH_RUNAPP}' is already persistently running on its allocated tty, that tty will become the active tty"
+		>&2 printf "%15s%s\n" "" "- If '${PH_RUNAPP}' is already non-persistently running on its allocated tty, startup will fail"
+		>&2 printf "%15s%s\n" "" "- If '${PH_RUNAPP}' is already running on a pseudo-terminal, that instance will be replaced by a new instance on its allocated tty"
+		>&2 printf "%15s%s\n" "" "- 'PieHelper' will always activate persistence for itself before starting on its allocated tty"
+		>&2 printf "%9s%s\n" "" "-p allows switching both the start mode for '${PH_RUNAPP}' from the default 'tty' setting to 'pts' to"
+		>&2 printf "%9s%s\n" "" "   start an instance of '${PH_RUNAPP}' on a pseudo-terminal instead of on its allocated tty"
+		>&2 printf "%12s%s\n" "" "- Specifying -p is optional"
+		>&2 printf "%12s%s\n" "" "- Additionally, the following rule(s) also apply when starting '${PH_RUNAPP}' in 'pts' mode :"
+		>&2 printf "%15s%s\n" "" "- If '${PH_RUNAPP}' is already persistently running on a pseudo-terminal, startup will be skipped but succeed with a warning"
+		>&2 printf "%15s%s\n" "" "- If '${PH_RUNAPP}' is already non-persistently running on a pseudo-terminal, startup will fail"
+		>&2 printf "%15s%s\n" "" "- If '${PH_RUNAPP}' is already running on its allocated tty, that instance will be replaced by a new instance on a pseudo-terminal"
+		>&2 printf "%9s%s\n" "" "-m allows starting '${PH_RUNAPP}' directly in menu [menu] instead of the default menu which is the current value of"
+		>&2 printf "%9s%s\n" "" "   PieHelper option 'PH_PIEH_CMD_OPTS'"
+		>&2 printf "%12s%s\n" "" "- If 'PH_PIEH_CMD_OPTS' has no value, it will priorly be set to 'Main'"
+		>&2 printf "%12s%s\n" "" "- Specifying -m is optional"
+		>&2 printf "%12s%s\n" "" "- Allowed values for [menu] are :"
+		>&2 printf "%15s%s\n" "" "- 'Main' or 'Controllers' or 'Apps' or 'Advanced' or 'Settings'"
+		>&2 printf "%15s%s\n" "" "- 'PS3' or 'PS4' or 'XBOX360'"
+		>&2 printf "%15s%s\n" "" "- 'AppManagement' or 'AppManagement_[appname]' where [appname] is the name of a supported application, e.g. 'AppManagement_PieHelper'"
+		>&2 printf "%15s%s\n" "" "- 'OptsManagement' or 'OptsManagement_[appname]' where [appname] is the name of a supported application, e.g. 'OptsManagement_PieHelper'"
+		>&2 printf "%15s%s\n" "" "- 'TTYManagement' or 'TTYManagement_[appname]' where [appname] is the name of a supported application, e.g. 'TTYManagement_PieHelper'"
+		>&2 printf "%12s%s\n" "" "- Specifying [menu] is optional"
+		>&2 printf "%15s%s\n" "" "- Omitting a value for [menu] will revert to using the default"
+		>&2 printf "%12s%s\033[0;0m\n" "" "- This option will be ignored when switching to an active persistent instance of '${PH_RUNAPP}'"
+		>&2 printf "\n"
+		OPTIND="${PH_OLDOPTIND}"
 		OPTARG="${PH_OLDOPTARG}"
 		exit 1 ;;
-        esac
+	esac
 done
 OPTIND="${PH_OLDOPTIND}"
 OPTARG="${PH_OLDOPTARG}"
 
 [[ -z "${PH_MODE}" ]] && \
-	PH_MODE="normal"
-printf "\n\033[1;36m%s\033[0;0m\n\n" "- Checking the requirements to stop '${PH_STOPAPP}'"
-PH_STOPAPP_STR_TTY="$(ph_get_app_tty_from_app_name "${PH_STOPAPP}")"
-PH_FG_CONSOLE="$("${PH_SUDO}" fgconsole 2>/dev/null)"
-if [[ "${PH_FG_CONSOLE}" -ne "${PH_STOPAPP_STR_TTY}" ]]
+	PH_MODE="tty"
+"stop${PH_STOPAPPL}.sh" || \
+	exit 1
+if [[ "${PH_MODE}" == "tty" ]]
 then
-	ph_set_result -m "Could not stop '${PH_STOPAPP}' since the currently active tty is not allocated to '${PH_STOPAPP}'"
-	ph_run_with_rollback -c false -m "Could not stop"
+	"start${PH_RUNAPPL}.sh" -m "${PH_MENU}"
 else
-	ph_run_with_rollback -c true
-	ph_set_result -t -r 0
-	ph_show_result
-	"stop${PH_STOPAPPL}.sh" || \
-		exit 1
-	if [[ "${PH_MODE}" == "normal" ]]
-	then
-		"start${PH_RUNAPPL}.sh" -m "${PH_MENU}"
-	else
-		"start${PH_RUNAPPL}.sh" -p -m "${PH_MENU}"
-	fi
+	"start${PH_RUNAPPL}.sh" -p -m "${PH_MENU}"
 fi
 exit "${?}"
diff --git a/files/templates/RestartScript.template b/files/templates/RestartScript.template
--- a/files/templates/RestartScript.template
+++ b/files/templates/RestartScript.template
@@ -2,50 +2,65 @@
 # Run '#PH_APP#' restart action (by Davy Keppens on 04/10/2018)
 # Enable/Disable debug by running 'confpieh_ph.sh -p debug -m restart#PH_APPL#.sh'
 
-. "$(dirname "$0" 2>/dev/null)/app/main.sh" || \
-	exit "$?" && \
+. "$(dirname "${0}" 2>/dev/null)/app/main.sh" || \
+	exit 1 && \
 	set +x
 
 #set -x
 
-declare PH_RUNAPP="#PH_APP#"
-declare PH_STOPAPP="$PH_RUNAPP"
-declare PH_OPTION=""
-declare PH_OLDOPTARG="$OPTARG"
-declare -i PH_OLDOPTIND="$OPTIND"
-declare -l PH_RUNAPPL="${PH_RUNAPP:0:4}"
-declare -l PH_STOPAPPL="${PH_STOPAPP:0:4}"
+declare PH_RUNAPP
+declare PH_STOPAPP
+declare PH_OPTION
+declare PH_OLDOPTARG
+declare -i PH_OLDOPTIND
+declare -l PH_RUNAPPL
+declare -l PH_STOPAPPL
+
+PH_OLDOPTARG="${OPTARG}"
+PH_OLDOPTIND="${OPTIND}"
+PH_RUNAPP="#PH_APP#"
+PH_STOPAPP="${PH_RUNAPP}"
+PH_OPTION=""
+PH_RUNAPPL="${PH_RUNAPP:0:4}"
+PH_STOPAPPL="${PH_STOPAPP:0:4}"
 
 OPTIND="1"
 
-while getopts h PH_OPTION 2>/dev/null
+while getopts :h PH_OPTION
 do
-        case "$PH_OPTION" in *)
-                >&2 printf "\n\033[36m%s%s%s\033[0m\n" "Usage : restart" "$PH_RUNAPPL" ".sh | -h"
-                >&2 printf "\n"
-                >&2 printf "%3s%s\n" "" "Where -h displays this usage"
-                >&2 printf "%9s%s\n" "" "- Running this script without parameters will stop an instance of '$PH_STOPAPP' running on it's allocated TTY"
-                >&2 printf "%9s%s\n" "" "  If successful, '$PH_RUNAPP' will be restarted on the same TTY and that TTY will become the active TTY"
-                >&2 printf "%12s%s\n" "" "- The first unallocated TTY will be automatically assigned to any application without a TTY that attempts to start"
-                >&2 printf "%12s%s\n" "" "- A TTY is only deallocated when an application is removed from PieHelper"
-                >&2 printf "%12s%s\n" "" "- If an application in need of a TTY attempts to start but all TTY's are already allocated, startup will fail"
-                >&2 printf "%12s%s\n" "" "- Persistence will be ignored when stopping '$PH_STOPAPP' since the stop command is being issued by a restart"
-                >&2 printf "%12s%s\n" "" "- At any application start, all other running integrated applications will first be stopped"
-                >&2 printf "%12s%s\n" "" "  Two exceptions to this rule exist:"
-                >&2 printf "%15s%s\n" "" "- PieHelper starting on a pseudo-terminal will never stop running applications"
-                >&2 printf "%15s%s\n" "" "- Applications marked as persistent remain online"
-                >&2 printf "%12s%s\n" "" "- Additionally, the following rules apply to the stop of '$PH_STOPAPP' :"
-                >&2 printf "%15s%s\n" "" "- If no active instance of '$PH_STOPAPP' can be found on it's allocated TTY or"
-                >&2 printf "%15s%s\n" "" "  the TTY for '$PH_STOPAPP' cannot be determined, stop will be skipped but succeed with a warning"
-                >&2 printf "\n"
-                OPTIND="$PH_OLDOPTIND"
-		OPTARG="$PH_OLDOPTARG"
+	case "${PH_OPTION}" in *)
+		>&2 printf "\n\033[1;36m%s\033[0;0m\n" "Usage : restart${PH_RUNAPPL}.sh | -h"
+		>&2 printf "\n"
+		>&2 printf "%3s\033[1;37m%s\n" "" "Where -h displays this usage"
+		>&2 printf "%9s%s\n" "" "- Running this script without parameters will stop an instance of '${PH_STOPAPP}' running on its allocated tty"
+		>&2 printf "%12s%s\n" "" "- If '${PH_STOPAPP}' is not a supported application, stop will fail"
+		>&2 printf "%12s%s\n" "" "- If a tty is allocated to '${PH_STOPAPP}' it remains allocated"
+		>&2 printf "%15s%s\n" "" "- An applications tty is freed only when unintegrating the application"
+		>&2 printf "%12s%s\n" "" "- Persistence will be ignored when stopping '${PH_STOPAPP}' since the stop command is indirectly issued by a restart"
+		>&2 printf "%12s%s\n" "" "- Additionally, the following rule(s) also apply when stopping '${PH_STOPAPP}' :"
+		>&2 printf "%15s%s\n" "" "- If no active instance of '${PH_STOPAPP}' can be found on its allocated tty, stop will be skipped but succeed with a warning"
+		>&2 printf "%9s%s\n" "" "  If successful, '${PH_RUNAPP}' will be restarted on the same tty and that tty will become the active tty"
+		>&2 printf "%12s%s\n" "" "- If '${PH_RUNAPP}' is not an integrated application, startup will fail"
+		>&2 printf "%12s%s\n" "" "- If '${PH_RUNAPP}' does not have a tty allocated when starting, the first unallocated tty will automatically be allocated to '${PH_RUNAPP}'"
+		>&2 printf "%15s%s\n" "" "- If an application in need of a tty attempts to start but all ttys are already allocated, startup will fail"
+		>&2 printf "%12s%s\n" "" "- At any application start, all other running integrated applications will first be stopped"
+		>&2 printf "%12s%s\n" "" "  Two exceptions to this rule exist:"
+		>&2 printf "%15s%s\n" "" "- Applications marked as persistent remain online"
+		>&2 printf "%15s%s\n" "" "- 'PieHelper' will not stop any running applications when starting in 'pts' mode"
+		>&2 printf "%12s%s\n" "" "- 'PieHelper' will always terminate after any other application starts successfully"
+		>&2 printf "%12s%s\n" "" "- Additionally, the following rule(s) also apply when starting '${PH_RUNAPP}' :"
+		>&2 printf "%15s%s\n" "" "- If '${PH_RUNAPP}' is already persistently running on its allocated tty, that tty will become the active tty"
+		>&2 printf "%15s%s\033[0;0m\n" "" "- If '${PH_RUNAPP}' is already non-persistently running on its allocated tty, startup will fail"
+		>&2 printf "\n"
+		OPTIND="${PH_OLDOPTIND}"
+		OPTARG="${PH_OLDOPTARG}"
 		exit 1 ;;
-        esac
+	esac
 done
-OPTIND="$PH_OLDOPTIND"
-OPTARG="$PH_OLDOPTARG"
+OPTIND="${PH_OLDOPTIND}"
+OPTARG="${PH_OLDOPTARG}"
 
-"stop$PH_STOPAPPL.sh" force || exit "$?"
-"start$PH_RUNAPPL.sh"
-exit "$?"
+"stop${PH_STOPAPPL}.sh" force || \
+	exit "${?}"
+"start${PH_RUNAPPL}.sh"
+exit "${?}"
diff --git a/files/templates/RestartScriptPieH.template b/files/templates/RestartScriptPieH.template
--- a/files/templates/RestartScriptPieH.template
+++ b/files/templates/RestartScriptPieH.template
@@ -1,91 +1,119 @@
-!/bin/bash
+#!/bin/bash
 # Run '#PH_APP#' restart action (by Davy Keppens on 04/10/2018)
 # Enable/Disable debug by running 'confpieh_ph.sh -p debug -m restart#PH_APPL#.sh'
 
-. "$(dirname "$0" 2>/dev/null)/app/main.sh" || \
-	exit "$?" && \
+. "$(dirname "${0}" 2>/dev/null)/app/main.sh" || \
+	exit 1 && \
 	set +x
 
 #set -x
 
-declare PH_RUNAPP="#PH_APP#"
-declare PH_STOPAPP="$PH_RUNAPP"
-declare PH_OPTION=""
-declare PH_MENU=""
-declare PH_MODE=""
-declare PH_OLDOPTARG="$OPTARG"
-declare -i PH_OLDOPTIND="$OPTIND"
-declare -l PH_RUNAPPL="${PH_RUNAPP:0:4}"
-declare -l PH_STOPAPPL="${PH_STOPAPP:0:4}"
+declare PH_RUNAPP
+declare PH_STOPAPP
+declare PH_MENU
+declare PH_MODE
+declare PH_OPTION
+declare PH_OLDOPTARG
+declare -i PH_OLDOPTIND
+declare -l PH_RUNAPPL
+declare -l PH_STOPAPPL
+
+PH_OLDOPTARG="${OPTARG}"
+PH_OLDOPTIND="${OPTIND}"
+PH_RUNAPP="#PH_APP#"
+PH_STOPAPP="${PH_RUNAPP}"
+PH_MENU=""
+PH_MODE=""
+PH_OPTION=""
+PH_RUNAPPL="${PH_RUNAPP:0:4}"
+PH_STOPAPPL="${PH_STOPAPP:0:4}"
 
 OPTIND="1"
 
-while getopts phm: PH_OPTION
+while getopts :m:ph PH_OPTION
 do
-	case "$PH_OPTION" in p)
-		[[ -n "$PH_MODE" ]] && (! "restart$PH_RUNAPPL.sh" -h) && OPTIND="$PH_OLDOPTIND" && \
-			OPTARG="$PH_OLDOPTARG" && exit 1
-		PH_MODE="pseudo" ;;
-			     m)
-		[[ -n "$PH_MENU" ]] && (! "restart$PH_RUNAPPL.sh" -h) && OPTIND="$PH_OLDOPTIND" && \
-			OPTARG="$PH_OLDOPTARG" && exit 1
-		if ! ph_screen_input "$OPTARG"
-		then
-			OPTARG="$PH_OLDOPTARG"
-			OPTIND="$PH_OLDOPTIND"
+	case "${PH_OPTION}" in p)
+		[[ -n "${PH_MODE}" ]] && \
+			(! "restart${PH_RUNAPPL}.sh" -h) && \
+			OPTIND="${PH_OLDOPTIND}" && \
+			OPTARG="${PH_OLDOPTARG}" && \
 			exit 1
-		fi
-		PH_MENU="$OPTARG" ;;
+		PH_MODE="pts" ;;
+			     m)
+		[[ -n "${PH_MENU}" || "${OPTARG}" != @(Main|@(Controller|App|Setting)s|Advanced|PS@(3|4)|XBOX360|@(App|Opts|TTY)Management*) ]] && \
+			(! "restart${PH_RUNAPPL}.sh" -h) && \
+			OPTIND="${PH_OLDOPTIND}" && \
+			OPTARG="${PH_OLDOPTARG}" && \
+			exit 1
+		PH_MENU="${OPTARG}" ;;
 			     *)
-                >&2 printf "\n\033[36m%s%s%s\033[0m\n" "Usage : restart" "$PH_RUNAPPL" ".sh '-p' '-m ['menu']' | -h"
-                >&2 printf "\n"
-                >&2 printf "%3s%s\n" "" "Where -h displays this usage"
-                >&2 printf "%9s%s\n" "" "- Running this script without parameters will stop an instance of '$PH_STOPAPP' running on it's allocated TTY"
-                >&2 printf "%9s%s\n" "" "  If successful, '$PH_RUNAPP' will be restarted on the same TTY and that TTY will become the active TTY"
-                >&2 printf "%12s%s\n" "" "- The first unallocated TTY will be automatically assigned to any application without a TTY that attempts to start"
-                >&2 printf "%12s%s\n" "" "- A TTY is only deallocated when an application is removed from PieHelper"
-                >&2 printf "%12s%s\n" "" "- If an application in need of a TTY attempts to start but all TTY's are already allocated, startup will fail"
-                >&2 printf "%12s%s\n" "" "- Persistence will be ignored when stopping '$PH_STOPAPP' since the stop command is being issued by a restart"
-                >&2 printf "%12s%s\n" "" "- At any application start, all other running integrated applications will first be stopped"
-                >&2 printf "%12s%s\n" "" "  Two exceptions to this rule exist:"
-                >&2 printf "%15s%s\n" "" "- PieHelper starting on a pseudo-terminal will never stop running applications"
-                >&2 printf "%15s%s\n" "" "- Applications marked as persistent remain online"
-                >&2 printf "%12s%s\n" "" "- Additionally, the following rules apply to the stop of '$PH_STOPAPP' :"
-                >&2 printf "%15s%s\n" "" "- If a '$PH_STOPAPP' instance is running on a pseudo-terminal, stop will fail"
-                >&2 printf "%15s%s\n" "" "- If no active instance of '$PH_STOPAPP' can be found on it's allocated TTY or"
-                >&2 printf "%15s%s\n" "" "  the TTY for '$PH_STOPAPP' cannot be determined, stop will be skipped but succeed with a warning"
-                >&2 printf "%9s%s\n" "" "-p allows setting both the stop and restart of '$PH_STOPAPP' to be executed on a pseudo-terminal instead of it's allocated TTY"
-                >&2 printf "%12s%s\n" "" "- Specifying -p is optional"
-                >&2 printf "%12s%s\n" "" "- The following rules replace these for a normal stop :"
-                >&2 printf "%15s%s\n" "" "- If a '$PH_STOPAPP' instance is running on it's allocated TTY, stop will fail"
-                >&2 printf "%15s%s\n" "" "- If no active instance of '$PH_STOPAPP' can be found on a pseudo-terminal, stop will be skipped but succeed with a warning"
-                >&2 printf "%12s%s\n" "" "- Additionally, the following rules apply to the start of '$PH_RUNAPP' :"
-		>&2 printf "%15s%s\n" "" "- As mentioned above, '$PH_RUNAPP' will not stop any other running applications when starting in this mode"
-                >&2 printf "%9s%s\n" "" "-m allows starting '$PH_RUNAPP' directly in menu [menu] instead of the default 'Main' menu"
-                >&2 printf "%12s%s\n" "" "- Specifying -m is optional"
-                >&2 printf "%12s%s\n" "" "- Allowed values for [menu] are 'Main', 'Controllers', 'Apps', 'Advanced', 'Settings', 'PS3', 'PS4', 'XBOX360', 'AppManagement',"
-                >&2 printf "%12s%s\n" "" "  'OptsManagement', 'AppManagement', 'TTYManagement', the name of any supported application, as well as one of 'OptsManagement', 'AppManagement' or 'TTYManagement' concatenated with '_' and"
-                >&2 printf "%12s%s\n" "" "  the name of any supported application, f.e. 'OptsManagement_Bash', 'AppManagement_PieHelper' or 'TTYManagement_Moonlight'"
-                >&2 printf "%15s%s\n" "" "- By default, the current value of option PH_PIEH_CMD_OPTS will be used"
-                >&2 printf "%18s%s\n" "" "- If PH_PIEH_CMD_OPTS has no value, it will be set to 'Main'"
-                >&2 printf "%15s%s\n" "" "- If an empty string is specified for [menu], the default will be used"
-                >&2 printf "\n"
-		OPTIND="$PH_OLDOPTIND"
-		OPTARG="$PH_OLDOPTARG"
-                exit 1 ;;
+		>&2 printf "\n\033[1;36m%s\033[0;0m\n" "Usage : restart${PH_RUNAPPL}.sh '-p' '-m ['menu']' | -h"
+		>&2 printf "\n"
+		>&2 printf "%3s\033[1;37m%s\n" "" "Where -h displays this usage"
+		>&2 printf "%9s%s\n" "" "- Running this script without parameters will stop an instance of '${PH_STOPAPP}' running on its allocated tty"
+		>&2 printf "%12s%s\n" "" "- If '${PH_STOPAPP}' is not a supported application, stop will fail"
+		>&2 printf "%12s%s\n" "" "- If a tty is allocated to '${PH_STOPAPP}' it remains allocated"
+		>&2 printf "%15s%s\n" "" "- An applications tty is freed only when unintegrating the application"
+		>&2 printf "%12s%s\n" "" "- Persistence will be ignored when stopping '${PH_STOPAPP}' since the stop command is indirectly issued by a restart"
+		>&2 printf "%12s%s\n" "" "- Additionally, the following rule(s) also apply when stopping '${PH_STOPAPP}' in 'tty' mode :"
+		>&2 printf "%15s%s\n" "" "- If no active instance of '${PH_STOPAPP}' can be found on its allocated tty, stop will be skipped but succeed with a warning"
+		>&2 printf "%15s%s\n" "" "- If '${PH_STOPAPP}' is running on a pseudo-terminal, stop will fail"
+		>&2 printf "%9s%s\n" "" "  If successful, '${PH_RUNAPP}' will be restarted on the same tty and that tty will become the active tty"
+		>&2 printf "%12s%s\n" "" "- If '${PH_RUNAPP}' is not an integrated application, startup will fail"
+		>&2 printf "%12s%s\n" "" "- If '${PH_RUNAPP}' does not have a tty allocated when starting, the first unallocated tty will automatically be allocated to '${PH_RUNAPP}'"
+		>&2 printf "%15s%s\n" "" "- If an application in need of a tty attempts to start but all ttys are already allocated, startup will fail"
+		>&2 printf "%12s%s\n" "" "- At any application start, all other running applications will first be stopped"
+		>&2 printf "%12s%s\n" "" "  Two exceptions to this rule exist:"
+		>&2 printf "%15s%s\n" "" "- Applications marked as persistent remain online"
+		>&2 printf "%15s%s\n" "" "- 'PieHelper' will not stop any running applications when starting in 'pts' mode"
+		>&2 printf "%12s%s\n" "" "- 'PieHelper' will always terminate after any other application starts successfully"
+		>&2 printf "%12s%s\n" "" "- Additionally, the following rule(s) also apply when starting '${PH_RUNAPP}' in 'tty' mode :"
+		>&2 printf "%15s%s\n" "" "- If '${PH_RUNAPP}' is already persistently running on its allocated tty, that tty will become the active tty"
+		>&2 printf "%15s%s\n" "" "- If '${PH_RUNAPP}' is already non-persistently running on its allocated tty, startup will fail"
+		>&2 printf "%15s%s\n" "" "- If '${PH_RUNAPP}' is already running on a pseudo-terminal, that instance will be replaced by a new instance on its allocated tty"
+		>&2 printf "%15s%s\n" "" "- 'PieHelper' will always activate persistence for itself before starting on its allocated tty"
+		>&2 printf "%9s%s\n" "" "-p allows switching both the stop and restart mode from the default 'tty' setting to 'pts' to"
+		>&2 printf "%9s%s\n" "" "   stop and restart an instance of '${PH_STOPAPP}' which on a pseudo-terminal instead of on its allocated tty"
+		>&2 printf "%12s%s\n" "" "- Specifying -p is optional"
+		>&2 printf "%12s%s\n" "" "- Additionally, the following rule(s) also apply when stopping '${PH_STOPAPP}' in 'pts' mode :"
+		>&2 printf "%15s%s\n" "" "- If no active instance of '${PH_STOPAPP}' can be found on a pseudo-terminal, stop will be skipped but succeed with a warning"
+		>&2 printf "%15s%s\n" "" "- If '${PH_STOPAPP}' is running on its allocated tty, stop will fail"
+		>&2 printf "%12s%s\n" "" "- Additionally, the following rule(s) also apply when starting '${PH_RUNAPP}' in 'pts' mode :"
+		>&2 printf "%15s%s\n" "" "- If '${PH_RUNAPP}' is already persistently running on a pseudo-terminal, startup will be skipped but succeed with a warning"
+		>&2 printf "%15s%s\n" "" "- If '${PH_RUNAPP}' is already non-persistently running on a pseudo-terminal, startup will fail"
+		>&2 printf "%15s%s\n" "" "- If '${PH_RUNAPP}' is already running on its allocated tty, that instance will be replaced by a new instance on a pseudo-terminal"
+		>&2 printf "%9s%s\n" "" "-m allows starting '${PH_RUNAPP}' directly in menu [menu] instead of the default menu which is the current value of"
+		>&2 printf "%9s%s\n" "" "   PieHelper option 'PH_PIEH_CMD_OPTS'"
+		>&2 printf "%12s%s\n" "" "- If 'PH_PIEH_CMD_OPTS' has no value, it will priorly be set to 'Main'"
+		>&2 printf "%12s%s\n" "" "- Specifying -m is optional"
+		>&2 printf "%12s%s\n" "" "- Allowed values for [menu] are :"
+		>&2 printf "%15s%s\n" "" "- 'Main' or 'Controllers' or 'Apps' or 'Advanced' or 'Settings'"
+		>&2 printf "%15s%s\n" "" "- 'PS3' or 'PS4' or 'XBOX360'"
+		>&2 printf "%15s%s\n" "" "- 'AppManagement' or 'AppManagement_[appname]' where [appname] is the name of a supported application, e.g. 'AppManagement_PieHelper'"
+		>&2 printf "%15s%s\n" "" "- 'OptsManagement' or 'OptsManagement_[appname]' where [appname] is the name of a supported application, e.g. 'OptsManagement_PieHelper'"
+		>&2 printf "%15s%s\n" "" "- 'TTYManagement' or 'TTYManagement_[appname]' where [appname] is the name of a supported application, e.g. 'TTYManagement_PieHelper'"
+		>&2 printf "%12s%s\n" "" "- Specifying [menu] is optional"
+		>&2 printf "%15s%s\n" "" "- Omitting a value for [menu] will revert to using the default"
+		>&2 printf "%12s%s\033[0;0m\n" "" "- This option will be ignored when switching to an active persistent instance of '${PH_RUNAPP}'"
+		>&2 printf "\n"
+		OPTIND="${PH_OLDOPTIND}"
+		OPTARG="${PH_OLDOPTARG}"
+		exit 1 ;;
 	esac
 done
-OPTIND="$PH_OLDOPTIND"
-OPTARG="$PH_OLDOPTARG"
+OPTIND="${PH_OLDOPTIND}"
+OPTARG="${PH_OLDOPTARG}"
 
-[[ -z "$PH_MODE" ]] && PH_MODE="normal"
-
-if [[ "$PH_MODE" == "normal" ]]
+[[ -z "${PH_MODE}" ]] && \
+	PH_MODE="tty"
+if [[ "${PH_MODE}" == "tty" ]]
 then
-	"stop$PH_STOPAPPL.sh" force || exit "$?"
-	"start$PH_RUNAPPL.sh" -m "$PH_MENU"
+	"stop${PH_STOPAPPL}.sh" force || \
+		exit 1
+	"start${PH_RUNAPPL}.sh" -m "${PH_MENU}"
 else
-	"stop$PH_STOPAPPL.sh" -p || exit "$?"
-	"start$PH_RUNAPPL.sh" -p -m "$PH_MENU"
+	"stop${PH_STOPAPPL}.sh" -p || \
+		exit 1
+	"start${PH_RUNAPPL}.sh" -p -m "${PH_MENU}"
 fi
-exit "$?"
+exit "${?}"
diff --git a/files/templates/StartScript.template b/files/templates/StartScript.template
--- a/files/templates/StartScript.template
+++ b/files/templates/StartScript.template
@@ -3,7 +3,7 @@
 # Enable/Disable debug by running 'confpieh_ph.sh -p debug -m start#PH_APPL#.sh'
 
 . "$(dirname "${0}" 2>/dev/null)/app/main.sh" || \
-	exit "${?}" && \
+	exit 1 && \
 	set +x
 
 #set -x
@@ -12,27 +12,23 @@ declare PH_i
 declare PH_RUNAPP
 declare PH_RUNAPP_STATE
 declare PH_EXCEPTION
-declare PH_STOPAPPS
 declare PH_OPTION
 declare PH_OLDOPTARG
 declare -i PH_OLDOPTIND
 declare -i PH_RUNAPP_TTY
-declare -i PH_PIEH_TTY
 declare -i PH_FG_CONSOLE
 declare -l PH_RUNAPPL
 declare -u PH_RUNAPPU
 
+PH_OLDOPTARG="${OPTARG}"
+PH_OLDOPTIND="${OPTIND}"
 PH_i=""
 PH_RUNAPP="#PH_APP#"
 PH_RUNAPP_STATE=""
 PH_EXCEPTION=""
-PH_STOPAPPS="None"
 PH_OPTION=""
-PH_OLDOPTARG="${OPTARG}"
-PH_OLDOPTIND="${OPTIND}"
 PH_RUNAPP_TTY="0"
-PH_PIEH_TTY="0"
-PH_FG_CONSOLE="0"
+PH_FG_CONSOLE="$("${PH_SUDO}" fgconsole 2>/dev/null)"
 PH_RUNAPPL="${PH_RUNAPP:0:4}"
 PH_RUNAPPU="${PH_RUNAPP:0:4}"
 
@@ -40,47 +36,43 @@ OPTIND="1"
 
 while getopts :h PH_OPTION
 do
-        case "${PH_OPTION}" in *)
-                >&2 printf "\n\033[1;36m%s\033[0;0m\n" "Usage : start${PH_RUNAPPL}.sh | -h"
-                >&2 printf "\n"
-                >&2 printf "%3s\033[1;37m%s\n" "" "Where -h displays this usage"
-                >&2 printf "%9s%s\n" "" "- Running this script without parameters will start a new instance of '${PH_RUNAPP}' on its allocated tty and that tty will become the active tty"
-                >&2 printf "%12s%s\n" "" "- The first unallocated tty will be automatically assigned to any application without a tty that attempts to start"
-                >&2 printf "%12s%s\n" "" "- A tty is only deallocated when an application is removed from PieHelper"
-                >&2 printf "%12s%s\n" "" "- If an application in need of a tty attempts to start but all ttys are already allocated, startup will fail"
-                >&2 printf "%12s%s\n" "" "- At any application start, all other running integrated applications will first be stopped"
-                >&2 printf "%12s%s\n" "" "  Two exceptions to this rule exist :"
-                >&2 printf "%15s%s\n" "" "- PieHelper starting on a pseudo-terminal will never stop running applications"
-                >&2 printf "%15s%s\n" "" "- Applications marked as persistent remain online" 
-                >&2 printf "%12s%s\n" "" "- Additionally, the following rules apply to the start of '${PH_RUNAPP}' :"
-                >&2 printf "%15s%s\n" "" "- '${PH_RUNAPP}' must be an integrated application or startup will fail"
-                >&2 printf "%15s%s\n" "" "- If a persistent '${PH_RUNAPP}' instance is already running on that tty, that tty will become the active tty"
-                >&2 printf "%15s%s\033[0;0m\n" "" "- If a non-persistent '${PH_RUNAPP}' instance is already running on that tty, startup will fail"
-                >&2 printf "\n"
-                OPTIND="${PH_OLDOPTIND}"
+	case "${PH_OPTION}" in *)
+		>&2 printf "\n\033[1;36m%s\033[0;0m\n" "Usage : start${PH_RUNAPPL}.sh | -h"
+		>&2 printf "\n"
+		>&2 printf "%3s\033[1;37m%s\n" "" "Where -h displays this usage"
+		>&2 printf "%9s%s\n" "" "- Running this script without parameters will start a new instance of '${PH_RUNAPP}' on its allocated tty and that tty will become the active tty"
+		>&2 printf "%12s%s\n" "" "- If '${PH_RUNAPP}' is not an integrated application, startup will fail"
+		>&2 printf "%12s%s\n" "" "- If '${PH_RUNAPP}' does not have a tty allocated when starting, the first unallocated tty will automatically be allocated to '${PH_RUNAPP}'"
+		>&2 printf "%15s%s\n" "" "- If an application in need of a tty attempts to start but all ttys are already allocated, startup will fail"
+		>&2 printf "%12s%s\n" "" "- At any application start, all other running applications will first be stopped"
+		>&2 printf "%12s%s\n" "" "  Two exceptions to this rule exist :"
+		>&2 printf "%15s%s\n" "" "- Applications marked as persistent remain online" 
+		>&2 printf "%15s%s\n" "" "- 'PieHelper' will not stop any running applications when starting in 'pts' mode"
+		>&2 printf "%12s%s\n" "" "- 'PieHelper' will always terminate after any other application starts successfully"
+		>&2 printf "%12s%s\n" "" "- Additionally, the following rule(s) also apply when starting '${PH_RUNAPP}' :"
+		>&2 printf "%15s%s\n" "" "- If '${PH_RUNAPP}' is already persistently running on its allocated tty, that tty will become the active tty"
+		>&2 printf "%15s%s\033[0;0m\n" "" "- If '${PH_RUNAPP}' is already non-persistently running on its allocated tty, startup will fail"
+		>&2 printf "\n"
+		OPTIND="${PH_OLDOPTIND}"
 		OPTARG="${PH_OLDOPTARG}"
 		exit 1 ;;
-        esac
+	esac
 done
 OPTIND="${PH_OLDOPTIND}"
 OPTARG="${PH_OLDOPTARG}"
 
-printf "\n\033[1;36m%s\033[0;0m\n\n" "- Checking the requirements to start '${PH_RUNAPP}'"
-PH_PIEH_TTY="$(ph_get_app_tty_from_app_name PieHelper)"
-PH_RUNAPP_STATE="$(ph_get_app_state_from_app_name "${PH_RUNAPP}")"
-PH_FG_CONSOLE="$("${PH_SUDO}" fgconsole 2>/dev/null)"
+printf "\n\033[1;36m%s\033[0;0m\n\n" "- Starting '${PH_RUNAPP}'"
 if [[ "$("${PH_SUDO}" cat "/proc/${PPID}/comm" 2>/dev/null)" != restart*sh ]]
 then
-	if [[ "${PH_RUNAPP_STATE}" == @(Integrated|Halted|Running) ]]
-	then
-		ph_run_with_rollback -c true
-	else
+	printf "%8s%s\033[1;33m%s\033[0;0m\n" "" "--> Checking the application state of " "'${PH_RUNAPP}'"
+	PH_RUNAPP_STATE="$(ph_get_app_state_from_app_name "${PH_RUNAPP}")"
+	case "${PH_RUNAPP_STATE}" in Integrated|Halted|Running)
+		ph_run_with_rollback -c true -m "${PH_RUNAPP_STATE}" ;;
+				*)
 		ph_set_result -m "Could not start '${PH_RUNAPP}' since it's not an integrated application"
 		ph_run_with_rollback -c false || \
-			exit 1
-	fi
-else
-	ph_run_with_rollback -c true
+			exit 1 ;;
+	esac
 fi
 printf "%8s%s\n" "" "--> Checking for running applications"
 if [[ "$("${PH_SUDO}" cat "/proc/${PPID}/comm" 2>/dev/null)" == +(?)to+(?).sh ]]
@@ -89,90 +81,100 @@ then
 			print substr($1,5,length($1)-7) \
 		}' "${PH_SCRIPTS_DIR}/$("$PH_SUDO" cat "/proc/${PPID}/comm" 2>/dev/null)" 2>/dev/null)"
 fi
-for PH_i in $(confapps_ph.sh -p list -k run 2>/dev/null | grep -v Skipping | tail -n +4 | tac | tail -n +4 | \
+declare -a PH_STOP_APPS
+if ! read -r -a PH_STOP_APPS < <(confapps_ph.sh -p list -k run 2>/dev/null | tail -n +4 | tac | tail -n +4 | \
 	nawk -v runappl="^${PH_RUNAPPL}$" -v except="^${PH_EXCEPTION}$" 'BEGIN { \
 			FS = "\x27" ; \
 			ORS = " " \
 		} \
+		$0 ~ /Skipping/ { \
+			next \
+		} \
 		$2 !~ /^None$/ && tolower(substr($2,1,4)) !~ except && tolower(substr($2,1,4)) !~ runappl { \
 			print $2 \
 	}')
-do
-	if [[ "${PH_STOPAPPS}" != "None" ]]
-	then
-		PH_STOPAPPS="${PH_STOPAPPS} ${PH_i}"
-	else
-		PH_STOPAPPS="${PH_i}"
-	fi
-done
-if [[ "${PH_STOPAPPS}" == "None" ]]
 then
-	ph_run_with_rollback -c true "${PH_STOPAPPS}"
-	PH_STOPAPPS=""
+	unset PH_STOP_APPS
+	ph_set_result -m "An error occurred trying to determine the currently running applications"
+	ph_run_with_rollback -c false -m "Could not determine"
+	exit "${?}"
+fi
+if [[ "${#PH_STOP_APPS[@]}" -eq "0" ]]
+then
+	ph_run_with_rollback -c true "None"
 else
-	printf "%10s\033[33m%s\033[0m\n" "" "Warning : Will stop the following currently running aplications '${PH_STOPPAPPS}'"
+	printf "%10s\033[33m%s\033[0m\n" "" "Warning : Stopping currently running application(s) ${PH_STOP_APPS[*]// / and }"
 	ph_set_result -r 0
 fi
-for PH_i in ${PH_STOPAPPS}
+for PH_i in "${!PH_STOP_APPS[@]}"
 do
-	if ! ph_do_app_action stop "${PH_i}"
+	if ! ph_run_with_rollback -c "ph_do_app_action stop '${PH_STOP_APPS[${PH_i}]}'"
 	then
-		ph_show_result
+		unset PH_STOP_APPS
 		exit "${?}"
-	else
-		[[ "$(ph_get_app_state_from_app_name "${PH_i}")" == "Running" ]] && \
-			PH_STOPAPPS="$(sed "s/^${PH_i} //g;s/ ${PH_i} / /g;s/ ${PH_i}$//g"<<<"${PH_STOPAPPS}" 2>/dev/null)"
 	fi
+	[[ "$(ph_get_app_state_from_app_name "${PH_STOP_APPS["${PH_i}"]}")" == "Running" ]] && \
+		unset PH_STOP_APPS["${PH_i}"]
 done
-[[ -z "${PH_STOPAPPS}" ]] && \
-	PH_STOPAPPS="None"
-ph_set_result -m "These applications were stopped '${PH_STOPAPPS}'"
+if [[ "${#PH_STOP_APPS[@]}" -eq "0" ]]
+then
+	ph_set_result -m "${PH_RUNAPP} has succesfully started and no other applications were stopped"
+else
+	ph_set_result -m "${PH_RUNAPP} has succesfully started after stopping application(s) ${PH_STOP_APPS[*]// / and }"
+fi
+unset PH_STOP_APPS
 ph_ensure_app_tty "${PH_RUNAPP}" || \
 	exit 1
+printf "%8s%s\033[1;33m%s\033[0;0m\n" "" "--> Determining the tty of " "'${PH_RUNAPP}'"
 PH_RUNAPP_TTY="$(ph_get_app_tty_from_app_name "${PH_RUNAPP}")"
+ph_run_with_rollback -c true -m "${PH_RUNAPP_TTY}"
 printf "%8s%s\033[1;33m%s\033[0;0m\n" "" "--> Checking for the presence of " "'${PH_RUNAPP}'"
 if [[ "${PH_RUNAPP_STATE}" != "Running" ]]
 then
 	ph_run_with_rollback -c true -m "Not found"
 	"${PH_SUDO}" rm "${PH_TMP_DIR}/Start.report" 2>/dev/null
-	if ph_do_app_action start "${PH_RUNAPP}" 2>&1 | tee -a "${PH_TMP_DIR}/Start.report"
+	if ph_run_with_rollback -c "ph_do_app_action start '${PH_RUNAPP}' 2>&1 \\| tee -a '${PH_TMP_DIR}/Start.report'"
 	then
 		[[ "${PH_RUNAPP}" == "Bash" ]] && \
 			exit 0
 	else
 		if [[ "${PH_FG_CONSOLE}" -ne "${PH_RUNAPP_TTY}" ]]
 		then
-			printf "%8s%s\033[1;33m%s\033[0;0m%s\n" "--> Displaying status report for failed " "'${PH_RUNAPP}'" " start"
+			printf "%8s%s\033[1;33m%s\033[1;37m\n" "" "--> Displaying logfile of the failed start of " "'${PH_RUNAPP}'"
 			if cat "${PH_TMP_DIR}/Start.report" 2>/dev/null
 			then
-				printf "\n"
-				ph_run_with_rollback -c true
+				printf "\033[0;0m\n\n"
+				ph_run_with_rollback -c true -m "${PH_TMP_DIR}/Start.report"
 			else
-				printf "%10s\033[33m%s\033[0m\n" "" "Warning : Could not display"
+				printf "%10s\033[0;33m%s\033[0;0m\n" "" "Warning : Could not display logfile '${PH_TMP_DIR}/Start.report' of the failed start of '${PH_RUNAPP}'"
 				ph_set_result -r 0
 			fi
 		else
-			"${PH_SUDO}" rm "${PH_TMP_DIR}/Start.report" 2>/dev/null
-			"${PH_SUDO}" chvt "${PH_PIEH_TTY}"
-			"${PH_SUDO}" systemctl stop "getty@tty${PH_RUNAPP_TTY}" >/dev/null 2>&1
-			"${PH_SUDO}" systemctl daemon-reload >/dev/null 2>&1
-			exit 1
+			:
+			####### use new fallback app option here
 		fi
+		"${PH_SUDO}" rm "${PH_TMP_DIR}/Start.report" 2>/dev/null
+		exit 1
 	fi
 	"${PH_SUDO}" rm "${PH_TMP_DIR}/Start.report" 2>/dev/null
 	ph_show_result
 else
 	if [[ "$(eval "echo -n \"\$PH_${PH_RUNAPPU}_PERSISTENT\"")" == "no" ]]
 	then
-		ph_set_result -m "Could not start '${PH_RUNAPP}' on 'tty${PH_RUNAPP_TTY}' since it's already non-persistently running"
-		ph_run_with_rollback -c false -m "Found" || \
-			exit 1
+		ph_set_result -m "Could not start '${PH_RUNAPP}' on tty${PH_RUNAPP_TTY} since it's already non-persistently running on that tty"
+		ph_run_with_rollback -c false -m "Found on tty${PH_RUNAPP_TTY}"
 	else
-		printf "%10s\033[33m%s\033[0m\n" "" "Warning : Found"
-		ph_set_result -r 0 -w -m "'${PH_RUNAPP}' is already persistently running on 'tty${PH_RUNAPP_TTY}' -> Switching to instance"
+		printf "%10s\033[33m%s\033[0m\n" "" "Warning : Already present on tty${PH_RUNAPP_TTY}"
+		ph_set_result -r 0 -w -m "Switching to tty${PH_RUNAPP_TTY} since '${PH_RUNAPP}' is already persistently running on that tty"
 		ph_show_result
 		sleep 2
-		"${PH_SUDO}" chvt "${PH_RUNAPP_TTY}"
+		if ! "${PH_SUDO}" chvt "${PH_RUNAPP_TTY}"
+		then
+			ph_set_result -m "An error occurred trying to switch to tty${PH_RUNAPP_TTY}"
+			false
+		else
+			true
+		fi
 	fi
 fi
 exit "${?}"
diff --git a/files/templates/StopScript.template b/files/templates/StopScript.template
--- a/files/templates/StopScript.template
+++ b/files/templates/StopScript.template
@@ -3,7 +3,7 @@
 # Enable/Disable debug by running 'confpieh_ph.sh -p debug -m stop#PH_APPL#.sh'
 
 . "$(dirname "${0}" 2>/dev/null)/app/main.sh" || \
-	exit "${?}" && \
+	exit 1 && \
 	set +x
 
 #set -x
@@ -28,7 +28,7 @@ OPTIND="1"
 
 while getopts :fh PH_OPTION
 do
-        case "${PH_OPTION}" in f)
+	case "${PH_OPTION}" in f)
 		[[ -n "${PH_PARAM}" ]] && \
 			(! "stop${PH_STOPAPPL}.sh" -h) && \
 			OPTIND="${PH_OLDOPTIND}" && \
@@ -36,39 +36,41 @@ do
 			exit 1
 		PH_PARAM="force" ;;
 			     *)
-                >&2 printf "\n\033[1;36m%s\033[0;0m\n" "Usage : stop${PH_STOPAPPL}.sh | -h"
-                >&2 printf "\n"
-                >&2 printf "%3s\033[1;37m%s\n" "" "Where -h displays this usage"
-                >&2 printf "%9s%s\n" "" "- Running this script without parameters will stop an instance of '${PH_STOPAPP}' running on its allocated tty"
-                >&2 printf "%12s%s\n" "" "- A tty is only deallocated when an application is removed from PieHelper"
-                >&2 printf "%12s%s\n" "" "- Additionally, the following rules apply to the stop of '${PH_STOPAPP}' :"
-                >&2 printf "%15s%s\n" "" "- If no active instance of '${PH_STOPAPP}' can be found on its allocated tty or"
-                >&2 printf "%15s%s\033[0;0m\n" "" "  the tty for '${PH_STOPAPP}' cannot be determined, stop will be skipped but succeed with a warning"
-                >&2 printf "\n"
-                OPTIND="${PH_OLDOPTIND}"
+		>&2 printf "\n\033[1;36m%s\033[0;0m\n" "Usage : stop${PH_STOPAPPL}.sh | -h"
+		>&2 printf "\n"
+		>&2 printf "%3s\033[1;37m%s\n" "" "Where -h displays this usage"
+		>&2 printf "%9s%s\n" "" "- Running this script without parameters will stop an instance of '${PH_STOPAPP}' running on its allocated tty"
+		>&2 printf "%12s%s\n" "" "- If '${PH_STOPAPP}' is not a supported application, stop will fail"
+		>&2 printf "%12s%s\n" "" "- If a tty is allocated to '${PH_STOPAPP}' it remains allocated"
+		>&2 printf "%15s%s\n" "" "- An applications tty is freed only when unintegrating the application"
+		>&2 printf "%12s%s\n" "" "- Additionally, the following rule(s) also apply when stopping '${PH_STOPAPP}' :"
+		>&2 printf "%15s%s\033[0;0m\n" "" "- If no active instance of '${PH_STOPAPP}' can be found on its allocated tty, stop will be skipped but succeed with a warning"
+		>&2 printf "\n"
+		OPTIND="${PH_OLDOPTIND}"
 		OPTARG="${PH_OLDOPTARG}"
 		exit 1 ;;
-        esac
+	esac
 done
 OPTIND="${PH_OLDOPTIND}"
 OPTARG="${PH_OLDOPTARG}"
 
 printf "\n\033[1;36m%s\033[0;0m\n\n" "- Stopping '${PH_STOPAPP}'"
-printf "%8s%s\033[1;33m%s\033[0;0m\n" "" "--> Checking the requirements to stop " "'${PH_STOPAPP}'"
+printf "%8s%s\033[1;33m%s\033[0;0m\n" "" "--> Checking the application state of " "'${PH_STOPAPP}'"
 PH_STOPAPP_STATE="$(ph_get_app_state_from_app_name "${PH_STOPAPP}")"
 case "${PH_STOPAPP_STATE}" in Supported|Integrated|Halted)
+	ph_set_result -w -m "Skipping the stop of '${PH_STOPAPP}' since it is already stopped"
 	ph_run_with_rollback -c true -m "Nothing to do"
 	ph_show_result ;;
 		Running)
-	ph_run_with_rollback -c true
+	ph_run_with_rollback -c true -m "${PH_STOPAPP_STATE}"
 	[[ -z "${PH_PARAM}" && "$("${PH_SUDO}" cat "/proc/${PPID}/comm" 2>/dev/null)" != @(start*sh|+(?)to+(?).sh|restart!("${PH_STOPAPPL}").sh) ]] && \
-			PH_PARAM="force"
-	if ph_do_app_action stop "${PH_STOPAPP}" ${PH_PARAM}
+		PH_PARAM="force"
+	if ph_run_with_rollback -c "ph_do_app_action stop '${PH_STOPAPP}' ${PH_PARAM}"
 	then
 		ph_show_result
 	fi ;;
 		*)
 	ph_set_result -m "Could not stop '${PH_STOPAPP}' since it's not a supported application"
-	ph_run_with_rollback -c false -m "Could not stop" ;;
+	ph_run_with_rollback -c false -m "${PH_STOPAPP_STATE}" ;;
 esac
 exit "${?}"
