More changes

diff --git a/files/templates/StartScriptPieH.template b/files/templates/StartScriptPieH.template
--- a/files/templates/StartScriptPieH.template
+++ b/files/templates/StartScriptPieH.template
@@ -2,202 +2,222 @@
 # Run '#PH_APP#' start action (by Davy Keppens on 04/10/2018)
 # Enable/Disable debug by running 'confpieh_ph.sh -p debug -m start#PH_APPL#.sh'
 
-. "$(dirname "$0" 2>/dev/null)/app/main.sh" || \
-	exit "$?" && \
+. "$(dirname "${0}" 2>/dev/null)/app/main.sh" || \
+	exit "${?}" && \
 	set +x
 
 #set -x
 
-declare PH_RUNAPP="#PH_APP#"
-declare PH_RUNAPP_STATE=""
-declare PH_APP_STATE=""
-declare PH_EXCEPTION=""
-declare PH_OPTION=""
-declare PH_INST=""
-declare PH_MODE=""
-declare PH_i=""
-declare PH_STOPAPPS="None"
-declare PH_OLDOPTARG="$OPTARG"
-declare -i PH_OLDOPTIND="$OPTIND"
-declare -i PH_RUNAPP_TTY="0"
-declare -i PH_MYPID="${$}"
-declare -i PH_FG_CONSOLE="0"
-declare -i PH_RECVD_FLAG="1"
-declare -i PH_RET_CODE="0"
-declare -l PH_RUNAPPL="${PH_RUNAPP:0:4}"
-declare -u PH_RUNAPPU="${PH_RUNAPP:0:4}"
+declare PH_i
+declare PH_RUNAPP
+declare PH_RUNAPP_STATE
+declare PH_APP_STATE
+declare PH_EXCEPTION
+declare PH_INST
+declare PH_MODE
+declare PH_STOPAPPS
+declare PH_OPTION
+declare PH_OLDOPTARG
+declare -i PH_OLDOPTIND
+declare -i PH_RUNAPP_TTY
+declare -i PH_MYPID
+declare -i PH_FG_CONSOLE
+declare -i PH_RECVD_FLAG
+declare -i PH_RET_CODE
+declare -l PH_RUNAPPL
+declare -u PH_RUNAPPU
 
-export PH_LAST_RETURN_GLOB="yes"
+declare -x PH_LAST_RETURN_GLOB
+
+PH_i=""
+PH_RUNAPP="#PH_APP#"
+PH_RUNAPP_STATE=""
+PH_APP_STATE=""
+PH_EXCEPTION=""
+PH_INST=""
+PH_MODE=""
+PH_STOPAPPS="None"
+PH_OPTION=""
+PH_OLDOPTARG="${OPTARG}"
+PH_OLDOPTIND="${OPTIND}"
+PH_RUNAPP_TTY="0"
+PH_MYPID="${$}"
+PH_FG_CONSOLE="0"
+PH_RECVD_FLAG="1"
+PH_RET_CODE="0"
+PH_RUNAPPL="${PH_RUNAPP:0:4}"
+PH_RUNAPPU="${PH_RUNAPP:0:4}"
+
+PH_LAST_RETURN_GLOB="yes"
 OPTIND="1"
 
-while getopts phm: PH_OPTION 2>/dev/null
+while getopts :phm: PH_OPTION
 do
-        case "$PH_OPTION" in p)
-		[[ -n "$PH_MODE" ]] && (! "start$PH_RUNAPPL.sh" -h) && OPTIND="$PH_OLDOPTIND" && \
-			OPTARG="$PH_OLDOPTARG" && exit 1
-                if [[ "$(tty)" != /dev/pts/* ]]
+        case "${PH_OPTION}" in p)
+		[[ -n "${PH_MODE}" ]] && \
+			(! "start${PH_RUNAPPL}.sh" -h) && \
+			OPTIND="${PH_OLDOPTIND}" && \
+			OPTARG="${PH_OLDOPTARG}" && \
+			exit 1
+                if [[ "$(tty 2>/dev/null)" != /dev/pts/* ]]
 		then
-			OPTIND="$PH_OLDOPTIND" && OPTARG="$PH_OLDOPTARG"
-			printf "\n\033[36m%s\033[0m\n" "- Executing '$PH_RUNAPP' start action prechecks"
-			ph_set_result -r 1 -m "Running this command from a pseudo-terminal is mandatory for option '-p'"
-			ph_show_result
-			exit "$?"
+			OPTIND="${PH_OLDOPTIND}"
+			OPTARG="${PH_OLDOPTARG}"
+			printf "\n\033[1;36m%s\033[0m\n\n" "- Checking the requirements to start '${PH_RUNAPP}'"
+			ph_set_result -m "Running this command from a pseudo-terminal is mandatory when using option '-p'"
+			ph_run_-with_rollback -c false -m "Could not start"
+			exit "${?}"
 		fi
 		PH_MODE="pseudo" ;;
 			   m)
-		[[ "$PH_RECVD_FLAG" -eq "0" ]] && (! "start$PH_RUNAPPL.sh" -h) && OPTIND="$PH_OLDOPTIND" && \
-			OPTARG="$PH_OLDOPTARG" && exit 1
-		PH_RECVD_FLAG="0"
-		if ! ph_screen_input "$OPTARG"
-		then
-			OPTIND="$PH_OLDOPTIND"
-			OPTARG="$PH_OLDOPTARG"
+		[[ "${PH_RECVD_FLAG}" -eq "0" || "${OPTARG}" != @(Main|@(Controller|App|Setting)s|Advanced|PS@(3|4)|XBOX360|@(App|Opts|TTY)Management*) ]] && \
+			(! "start${PH_RUNAPPL}.sh" -h) && \
+			OPTIND="${PH_OLDOPTIND}" && \
+			OPTARG="${PH_OLDOPTARG}" && \
 			exit 1
-		fi
-		if [[ "$OPTARG" != @(Main|Controllers|Apps|Advanced|Settings|PS3|PS4|XBOX360|AppManagement|OptsManagement|TTYManagement|OS|OSdefaults|$(nawk 'BEGIN { ORS = "|" } { print $1 "|" "OptsManagement_" $1 "|" "TTYManagement_" $1 "|" "AppManagement_" $1 }' "$PH_CONF_DIR/supported_apps")|) ]]
+		PH_RECVD_FLAG="0"
+		if [[ "${PH_PIEH_CMD_OPTS}" != "${OPTARG}" ]]
 		then
-			if ! "start$PH_RUNAPPL.sh" -h
+			if ! confopts_ph.sh -p set -a "${PH_RUNAPP}" -o PH_PIEH_CMD_OPTS="${OPTARG}"
 			then
-				OPTIND="$PH_OLDOPTIND"
-				OPTARG="$PH_OLDOPTARG"
+				OPTIND="${PH_OLDOPTIND}"
+				OPTARG="${PH_OLDOPTARG}"
 				exit 1
 			fi
-		fi
-		if [[ -n "$OPTARG" && "$PH_PIEH_CMD_OPTS" != "$OPTARG" ]]
-		then
-			if ! confopts_ph.sh -p set -a "$PH_RUNAPP" -o PH_PIEH_CMD_OPTS="$OPTARG"
-			then
-				OPTIND="$PH_OLDOPTIND"
-				OPTARG="$PH_OLDOPTARG"
-				exit 1
-			fi
-			export PH_PIEH_CMD_OPTS="$OPTARG"
+			export PH_PIEH_CMD_OPTS="${OPTARG}"
 		fi ;;
                            *)
-                >&2 printf "\n\033[36m%s%s%s\033[0m\n" "Usage : start" "$PH_RUNAPPL.sh" " '-m ['menu']' '-p' | -h"
+                >&2 printf "\n\033[1;36m%s%s%s\033[0;0m\n" "Usage : start${PH_RUNAPPL}.sh '-m ['menu']' '-p' | -h"
                 >&2 printf "\n"
-                >&2 printf "%3s%s\n" "" "Where -h displays this usage"
-                >&2 printf "%9s%s\n" "" "- Running this script without parameters will start a new instance of '$PH_RUNAPP' on it's allocated TTY and that TTY will become the active TTY"
-                >&2 printf "%12s%s\n" "" "- The first unallocated TTY will be automatically assigned to any application without a TTY that attempts to start"
-                >&2 printf "%12s%s\n" "" "- A TTY is only deallocated when an application is removed from PieHelper"
-                >&2 printf "%12s%s\n" "" "- If an application in need of a TTY attempts to start but all TTY's are already allocated, startup will fail"
+                >&2 printf "%3s\033[1;37m%s\n" "" "Where -h displays this usage"
+                >&2 printf "%9s%s\n" "" "- Running this script without parameters will start a new instance of '${PH_RUNAPP}' on its allocated tty and that tty will become the active tty"
+                >&2 printf "%12s%s\n" "" "- The first available tty will be automatically allocated to any application without a tty that attempts to start"
+                >&2 printf "%12s%s\n" "" "- A tty is only deallocated when an application is removed from PieHelper"
+                >&2 printf "%12s%s\n" "" "- If an application in need of a tty attempts to start but all ttys are already allocated, startup will fail"
                 >&2 printf "%12s%s\n" "" "- At any application start, all other running integrated applications will first be stopped"
                 >&2 printf "%12s%s\n" "" "  Two exceptions to this rule exist :"
                 >&2 printf "%15s%s\n" "" "- PieHelper starting on a pseudo-terminal will never stop running applications"
                 >&2 printf "%15s%s\n" "" "- Applications marked as persistent remain online"
-                >&2 printf "%12s%s\n" "" "- Additionally, the following rules apply to the start of '$PH_RUNAPP' :" 
-                >&2 printf "%15s%s\n" "" "- '$PH_RUNAPP' must be an integrated application or startup will fail"
-                >&2 printf "%15s%s\n" "" "- If a persistent '$PH_RUNAPP' instance is already running on that TTY, that TTY will become the active TTY"
-                >&2 printf "%15s%s\n" "" "- If a non-persistent '$PH_RUNAPP' instance is already running on that TTY, startup will fail"
-                >&2 printf "%15s%s\n" "" "- '$PH_RUNAPP' will always activate persistence for itself before starting on a TTY"
-                >&2 printf "%15s%s\n" "" "- '$PH_RUNAPP' will always terminate after any other application startup completes successfully"
-                >&2 printf "%15s%s\n" "" "- If a '$PH_RUNAPP' instance is already running on a pseudo-terminal, that instance will be replaced by the new instance on it's allocated TTY"
-                >&2 printf "%9s%s\n" "" "-p allows setting the start of '$PH_RUNAPP' to be executed on a pseudo-terminal instead of it's allocated TTY"
+                >&2 printf "%12s%s\n" "" "- Additionally, the following rules apply to the start of '${PH_RUNAPP}' :" 
+                >&2 printf "%15s%s\n" "" "- '${PH_RUNAPP}' must be an integrated application or startup will fail"
+                >&2 printf "%15s%s\n" "" "- If a persistent '${PH_RUNAPP}' instance is already running on that tty, that tty will become the active tty"
+                >&2 printf "%15s%s\n" "" "- If a non-persistent '${PH_RUNAPP}' instance is already running on that tty, startup will fail"
+                >&2 printf "%15s%s\n" "" "- '${PH_RUNAPP}' will always activate persistence for itself before starting on a tty"
+                >&2 printf "%15s%s\n" "" "- '${PH_RUNAPP}' will always terminate after any other application startup completes successfully"
+                >&2 printf "%15s%s\n" "" "- If a '${PH_RUNAPP}' instance is already running on a pseudo-terminal, that instance will be replaced by the new instance on its allocated tty"
+                >&2 printf "%9s%s\n" "" "-p allows setting the start of '${PH_RUNAPP}' to be executed on a pseudo-terminal instead of its allocated tty"
                 >&2 printf "%12s%s\n" "" "- Specifying -p is optional"
                 >&2 printf "%12s%s\n" "" "- The following rules replace these for a normal start :"
-                >&2 printf "%15s%s\n" "" "- '$PH_RUNAPP' must be an integrated application or startup will fail"
+                >&2 printf "%15s%s\n" "" "- '${PH_RUNAPP}' must be an integrated application or startup will fail"
                 >&2 printf "%15s%s\n" "" "- PieHelper will not stop any other running integrated applications before starting in this mode" 
-                >&2 printf "%15s%s\n" "" "- If a persistent '$PH_RUNAPP' pseudo-terminal instance is already running, startup will be skipped but succeed with a warning" 
-                >&2 printf "%15s%s\n" "" "- If a non-persistent '$PH_RUNAPP' pseudo-terminal instance is already running, startup will fail"
-                >&2 printf "%15s%s\n" "" "- If a '$PH_RUNAPP' instance is already running on it's allocated TTY, that instance will be replaced by the new pseudo-terminal instance"
-                >&2 printf "%9s%s\n" "" "-m allows starting '$PH_RUNAPP' directly in menu [menu] instead of the default 'Main' menu"
+                >&2 printf "%15s%s\n" "" "- If a persistent '${PH_RUNAPP}' pseudo-terminal instance is already running, startup will be skipped but succeed with a warning" 
+                >&2 printf "%15s%s\n" "" "- If a non-persistent '${PH_RUNAPP}' pseudo-terminal instance is already running, startup will fail"
+                >&2 printf "%15s%s\n" "" "- If a '${PH_RUNAPP}' instance is already running on its allocated tty, that instance will be replaced by the new pseudo-terminal instance"
+                >&2 printf "%9s%s\n" "" "-m allows starting '${PH_RUNAPP}' directly in menu [menu] instead of the default 'Main' menu"
                 >&2 printf "%12s%s\n" "" "- Specifying -m is optional"
                 >&2 printf "%12s%s\n" "" "- Allowed values for [menu] are 'Main', 'Controllers', 'Apps', 'Advanced', 'Settings', 'PS3', 'PS4', 'XBOX360', 'AppManagement',"
                 >&2 printf "%12s%s\n" "" "  'OptsManagement', 'AppManagement', 'TTYManagement', the name of any supported application, as well as one of 'OptsManagement', 'AppManagement' or 'TTYManagement' concatenated with '_' and"
                 >&2 printf "%12s%s\n" "" "  the name of any supported application, f.e. 'OptsManagement_Bash', 'AppManagement_PieHelper' or 'TTYManagement_Moonlight'"
-                >&2 printf "%15s%s\n" "" "- By default, the current value of option PH_PIEH_CMD_OPTS will be used"
-                >&2 printf "%18s%s\n" "" "- If PH_PIEH_CMD_OPTS has no value, it will be set to 'Main'"
+                >&2 printf "%15s%s\n" "" "- By default, the current value of option 'PH_PIEH_CMD_OPTS' will be used"
+                >&2 printf "%18s%s\n" "" "- If 'PH_PIEH_CMD_OPTS' has no value, it will be set to 'Main'"
                 >&2 printf "%15s%s\n" "" "- If an empty string is specified for [menu], the default will be used"
-                >&2 printf "%12s%s\n" "" "- This setting will be ignored if a persistent instance of '$PH_RUNAPP' is already active"
+                >&2 printf "%12s%s\033[0;0m\n" "" "- This setting will be ignored if a persistent instance of '${PH_RUNAPP}' is already active"
                 >&2 printf "\n"
-                OPTIND="$PH_OLDOPTIND"
-		OPTARG="$PH_OLDOPTARG"
+                OPTIND="${PH_OLDOPTIND}"
+		OPTARG="${PH_OLDOPTARG}"
 		exit 1 ;;
         esac
 done
-OPTIND="$PH_OLDOPTIND"
-OPTARG="$PH_OLDOPTARG"
+OPTIND="${PH_OLDOPTIND}"
+OPTARG="${PH_OLDOPTARG}"
 
-[[ -z "$PH_MODE" ]] && PH_MODE="normal"
-
-printf "\n\033[1;36m%s\033[1;33m%s\033[0;0m\n\n" "- Checking the requirements to start " "'${PH_RUNAPP}'" 
-PH_RUNAPP_STATE="$(ph_get_app_state_from_app_name "$PH_RUNAPP")"
-PH_FG_CONSOLE="$("$PH_SUDO" fgconsole 2>/dev/null)"
-if [[ "$("$PH_SUDO" cat "/proc/$PPID/comm")" != restart*sh ]]
+[[ -z "${PH_MODE}" ]] && \
+	PH_MODE="normal"
+printf "\n\033[1;36m%s\033[0;0m\n\n" "- Checking the requirements to start '${PH_RUNAPP}'" 
+PH_RUNAPP_STATE="$(ph_get_app_state_from_app_name "${PH_RUNAPP}")"
+PH_FG_CONSOLE="$("${PH_SUDO}" fgconsole 2>/dev/null)"
+if [[ "$("${PH_SUDO}" cat "/proc/${PPID}/comm" 2>/dev/null)" != restart*sh ]]
 then
-	printf "%8s%s\n" "" "--> Checking for '$PH_RUNAPP' integration"
-	if [[ "$PH_RUNAPP_STATE" == @(Integrated|Halted|Running) ]]
+	printf "%8s%s\n" "" "--> Checking for '${PH_RUNAPP}' integration"
+	if [[ "${PH_RUNAPP_STATE}" == @(Integrated|Halted|Running) ]]
 	then
-		ph_set_result -r "$?"
-		printf "%10s\033[32m%s\033[0m\n" "" "OK ('$PH_RUNAPP_STATE')"
+		ph_set_result -r "${?}"
+		printf "%10s\033[32m%s\033[0m\n" "" "OK ('${PH_RUNAPP_STATE}')"
 	else
-		ph_set_result -r "$?" -m "Integration is mandatory for '$PH_RUNAPP' start"
+		ph_set_result -r "${?}" -m "Integration is mandatory for '${PH_RUNAPP}' start"
 		printf "%10s\033[31m%s\033[0m\n" "" "ERROR : Invalid application state"
 		ph_show_result
-		exit "$?"
+		exit "${?}"
 	fi
 fi
-if [[ -z "$PH_PIEH_CMD_OPTS" ]]
+if [[ -z "${PH_PIEH_CMD_OPTS}" ]]
 then
-	if ! ph_set_option_to_value "$PH_RUNAPP" -r "PH_PIEH_CMD_OPTS'Main"
+	if ! ph_run_with_rollback -c "ph_set_option_to_value '${PH_RUNAPP}' -r \"PH_PIEH_CMD_OPTS'Main\""
 	then
-		ph_show_result
-		exit "$?"
+		exit "${?}"
 	fi
 fi
-if [[ "$PH_MODE" == "normal" ]]
+if [[ "${PH_MODE}" == "normal" ]]
 then
 	printf "%8s%s\n" "" "--> Checking for running applications"
-	if [[ "$("$PH_SUDO" cat "/proc/$PPID/comm")" == +(?)to+(?).sh ]]
+	if [[ "$("${PH_SUDO}" cat "/proc/${PPID}/comm")" == +(?)to+(?).sh ]]
 	then
-		PH_EXCEPTION="$(nawk '$1 ~ /^stop.*\.sh$/ { print substr($1,5,length($1)-7) }' "$PH_SCRIPTS_DIR/$("$PH_SUDO" cat "/proc/$PPID/comm")" 2>/dev/null)"
+		PH_EXCEPTION="$(nawk '$1 ~ /^stop.*\.sh$/ { print substr($1,5,length($1)-7) }' "${PH_SCRIPTS_DIR}/$("${PH_SUDO}" cat "/proc/${PPID}/comm")" 2>/dev/null)"
 	fi
-	for PH_i in $(confapps_ph.sh -p list -k run | grep -v Skipping | tail -n +4 | tac | tail -n +4 | nawk -v runappl=^"$PH_RUNAPPL"$ -v except=^"$PH_EXCEPTION"$ 'BEGIN { FS = "\x27" ; ORS = " " }
-												$2 !~ /^None$/ && tolower(substr($2,1,4)) !~ except && tolower(substr($2,1,4)) !~ runappl { print $2 }')
+	for PH_i in $(confapps_ph.sh -p list -k run | grep -v Skipping | tail -n +4 | tac | tail -n +4 | \
+		nawk -v runappl="^${PH_RUNAPPL}$" -v except="^${PH_EXCEPTION}$" 'BEGIN { \
+				FS = "\x27" ; \
+				ORS = " " \
+			} \
+			$2 !~ /^None$/ && tolower(substr($2,1,4)) !~ except && tolower(substr($2,1,4)) !~ runappl { \
+				print $2 \
+			}')
 	do
-		if [[ "$PH_STOPAPPS" != "None" ]]
+		if [[ "${PH_STOPAPPS}" != "None" ]]
 		then
-			PH_STOPAPPS="$PH_STOPAPPS $PH_i"
+			PH_STOPAPPS="${PH_STOPAPPS} ${PH_i}"
 		else
-			PH_STOPAPPS="$PH_i"
+			PH_STOPAPPS="${PH_i}"
 		fi
 	done
 	ph_set_result -r 0
-	if [[ "$PH_STOPAPPS" == "None" ]]
+	if [[ "${PH_STOPAPPS}" == "None" ]]
 	then
-		printf "%10s\033[32m%s\033[0m\n" "" "OK : ('$PH_STOPAPPS')"
+		printf "%10s\033[32m%s\033[0m\n" "" "OK : ('${PH_STOPAPPS}')"
 		PH_STOPAPPS=""
 	else
-		printf "%10s\033[33m%s\033[0m\n" "" "Warning : The following applications are running ('$PH_STOPAPPS') -> Stopping"
+		printf "%10s\033[33m%s\033[0m\n" "" "Warning : The following applications are running ('${PH_STOPAPPS}') -> Stopping"
 	fi
-	for PH_i in $(echo -n "$PH_STOPAPPS")
+	for PH_i in $(echo -n "${PH_STOPAPPS}")
 	do
-		if ! ph_do_app_action stop "$PH_i"
+		if ! ph_do_app_action stop "${PH_i}"
 		then
 			ph_show_result
-			exit "$?"
+			exit "${?}"
 		else
-			[[ "$(ph_get_app_state_from_app_name "$PH_i")" == "Running" ]] && PH_STOPAPPS="$(sed "s/^$PH_i //g;s/ $PH_i / /g;s/ $PH_i$//g" <<<"$PH_STOPAPPS" 2>/dev/null)"
+			[[ "$(ph_get_app_state_from_app_name "${PH_i}")" == "Running" ]] && \
+				PH_STOPAPPS="$(sed "s/^${PH_i} //g;s/ ${PH_i} / /g;s/ ${PH_i}$//g"<<<"${PH_STOPAPPS}" 2>/dev/null)"
 		fi
 	done
-	[[ -z "$PH_STOPAPPS" ]] && PH_STOPAPPS="None"
-	ph_set_result -m "The following applications were stopped ('$PH_STOPAPPS')"
-	ph_ensure_app_tty "$PH_RUNAPP"
-	PH_RUNAPP_TTY="$(ph_get_app_tty_from_app_name "$PH_RUNAPP")"
-	if [[ "$PH_RUNAPP_TTY" -le "1" || "$PH_RUNAPP_TTY" -gt "$PH_PIEH_MAX_TTYS" ]]
+	[[ -z "${PH_STOPAPPS}" ]] && \
+		PH_STOPAPPS="None"
+	ph_set_result -m "The following applications were stopped ('${PH_STOPAPPS}')"
+	ph_ensure_app_tty "${PH_RUNAPP}"
+	PH_RUNAPP_TTY="$(ph_get_app_tty_from_app_name "${PH_RUNAPP}")"
+	if [[ "${PH_RUNAPP_TTY}" -le "1" || "${PH_RUNAPP_TTY}" -gt "${PH_PIEH_MAX_TTYS}" ]]
 	then
-		ph_set_result -m "A valid TTY allocation is mandatory for '$PH_RUNAPP' start on a TTY"
+		ph_set_result -m "A valid TTY allocation is mandatory for '${PH_RUNAPP}' start on a tty"
 		ph_show_result
-		exit "$?"
+		exit "${?}"
 	fi
 else
-	printf "%8s%s\n" "" "--> Determining '$PH_RUNAPP' TTY"
-	PH_RUNAPP_TTY="$(ph_get_app_tty_from_app_name "$PH_RUNAPP")"
-	if [[ "$PH_RUNAPP_TTY" -ge "2" && "$PH_RUNAPP_TTY" -le "$PH_PIEH_MAX_TTYS" ]]
+	printf "%8s%s\n" "" "--> Determining '${PH_RUNAPP}' tty"
+	PH_RUNAPP_TTY="$(ph_get_app_tty_from_app_name "${PH_RUNAPP}")"
+	if [[ "${PH_RUNAPP_TTY}" -ge "2" && "${PH_RUNAPP_TTY}" -le "${PH_PIEH_MAX_TTYS}" ]]
 	then
-		printf "%10s\033[32m%s\033[0m\n" "" "OK ('TTY$PH_RUNAPP_TTY')"
+		printf "%10s\033[32m%s\033[0m\n" "" "OK ('tty${PH_RUNAPP_TTY}')"
 	else
-		printf "%10s\033[33m%s\033[0m\n" "" "Warning : Could not determine TTY"
+		printf "%10s\033[33m%s\033[0m\n" "" "Warning : Could not determine tty"
 	fi
 	ph_set_result -r 0
 fi
diff --git a/files/templates/StopScript.template b/files/templates/StopScript.template
--- a/files/templates/StopScript.template
+++ b/files/templates/StopScript.template
@@ -2,90 +2,73 @@
 # Run '#PH_APP#' stop action (by Davy Keppens on 04/10/2018)
 # Enable/Disable debug by running 'confpieh_ph.sh -p debug -m stop#PH_APPL#.sh'
 
-. "$(dirname "$0" 2>/dev/null)/app/main.sh" || \
-	exit "$?" && \
+. "$(dirname "${0}" 2>/dev/null)/app/main.sh" || \
+	exit "${?}" && \
 	set +x
 
 #set -x
 
-declare PH_STOPAPP="#PH_APP#"
-declare PH_STOPAPP_STATE=""
-declare PH_PARAM=""
-declare PH_OPTION=""
-declare PH_OLDOPTARG="$OPTARG"
-declare -i PH_OLDOPTIND="$OPTIND"
-declare -i PH_STOPAPP_TTY="0"
-declare -l PH_STOPAPPL="${PH_STOPAPP:0:4}"
+declare PH_STOPAPP
+declare PH_STOPAPP_STATE
+declare PH_PARAM
+declare PH_OPTION
+declare PH_OLDOPTARG
+declare -i PH_OLDOPTIND
+declare -l PH_STOPAPPL
+
+PH_OLDOPTARG="${OPTARG}"
+PH_OLDOPTIND="${OPTIND}"
+PH_STOPAPP="#PH_APP#"
+PH_STOPAPP_STATE=""
+PH_PARAM=""
+PH_OPTION=""
+PH_STOPAPPL="${PH_STOPAPP:0:4}"
 
 OPTIND="1"
 
-while getopts fh PH_OPTION 2>/dev/null
+while getopts :fh PH_OPTION
 do
-        case "$PH_OPTION" in f)
-		[[ -n "$PH_PARAM" ]] && (! "stop$PH_STOPAPPL.sh" -h) && OPTIND="$PH_OLDOPTIND" && \
-			OPTARG="$PH_OLDOPTARG" && exit 1
+        case "${PH_OPTION}" in f)
+		[[ -n "${PH_PARAM}" ]] && \
+			(! "stop${PH_STOPAPPL}.sh" -h) && \
+			OPTIND="${PH_OLDOPTIND}" && \
+			OPTARG="${PH_OLDOPTARG}" && \
+			exit 1
 		PH_PARAM="force" ;;
 			     *)
-                >&2 printf "\n\033[36m%s%s%s\033[0m\n" "Usage : stop" "$PH_STOPAPPL" ".sh | -h"
+                >&2 printf "\n\033[1;36m%s\033[0;0m\n" "Usage : stop${PH_STOPAPPL}.sh | -h"
                 >&2 printf "\n"
-                >&2 printf "%3s%s\n" "" "Where -h displays this usage"
-                >&2 printf "%9s%s\n" "" "- Running this script without parameters will stop an instance of '$PH_STOPAPP' running on it's allocated TTY"
-                >&2 printf "%12s%s\n" "" "- A TTY is only deallocated when an application is removed from PieHelper"
-                >&2 printf "%12s%s\n" "" "- Additionally, the following rules apply to the stop of '$PH_STOPAPP' :"
-                >&2 printf "%15s%s\n" "" "- If no active instance of '$PH_STOPAPP' can be found on it's allocated TTY or"
-                >&2 printf "%15s%s\n" "" "  the TTY for '$PH_STOPAPP' cannot be determined, stop will be skipped but succeed with a warning"
+                >&2 printf "%3s\033[1;37m%s\n" "" "Where -h displays this usage"
+                >&2 printf "%9s%s\n" "" "- Running this script without parameters will stop an instance of '${PH_STOPAPP}' running on its allocated tty"
+                >&2 printf "%12s%s\n" "" "- A tty is only deallocated when an application is removed from PieHelper"
+                >&2 printf "%12s%s\n" "" "- Additionally, the following rules apply to the stop of '${PH_STOPAPP}' :"
+                >&2 printf "%15s%s\n" "" "- If no active instance of '${PH_STOPAPP}' can be found on its allocated tty or"
+                >&2 printf "%15s%s\033[0;0m\n" "" "  the tty for '${PH_STOPAPP}' cannot be determined, stop will be skipped but succeed with a warning"
                 >&2 printf "\n"
-                OPTIND="$PH_OLDOPTIND"
-		OPTARG="$PH_OLDOPTARG"
+                OPTIND="${PH_OLDOPTIND}"
+		OPTARG="${PH_OLDOPTARG}"
 		exit 1 ;;
         esac
 done
-OPTIND="$PH_OLDOPTIND"
-OPTARG="$PH_OLDOPTARG"
+OPTIND="${PH_OLDOPTIND}"
+OPTARG="${PH_OLDOPTARG}"
 
-printf "\n\033[36m%s\033[0m\n\n" "- Executing '$PH_STOPAPP' stop action prechecks"
-PH_STOPAPP_STATE="$(ph_get_app_state_from_app_name "$PH_STOPAPP")"
-printf "%8s%s\n" "" "--> Checking for '$PH_STOPAPP' integration"
-if [[ "$PH_STOPAPP_STATE" == @(Integrated|Halted|Running) ]]
-then
-	ph_set_result -r "$?"
-	printf "%10s\033[32m%s\033[0m\n" "" "OK ('$PH_STOPAPP_STATE')"
-else
-	ph_set_result -r "$?" -m "Integration is mandatory for '$PH_STOPAPP' stop"
-	printf "%10s\033[31m%s\033[0m\n" "" "ERROR : Invalid application state"
-	ph_show_result
-	exit "$?"
-fi
-printf "%8s%s\n" "" "--> Determining '$PH_STOPAPP' TTY"
-PH_STOPAPP_TTY="$(ph_get_app_tty_from_app_name "$PH_STOPAPP")"
-if [[ "$PH_STOPAPP_TTY" -le "1" || "$PH_STOPAPP_TTY" -gt "$PH_PIEH_MAX_TTYS" ]]
-then
-	printf "%10s\033[33m%s\033[0m\n" "" "Warning : Could not determine TTY"
-	ph_set_result -r 0 -w -m "A valid TTY allocation is mandatory for '$PH_STOPAPP' stop"
-	ph_show_result
-	exit "$?"
-else
-	printf "%10s\033[32m%s\033[0m\n" "" "OK ('TTY$PH_STOPAPP_TTY')"
-	ph_set_result -r 0
-fi
-printf "%8s%s\n" "" "--> Checking for '$PH_STOPAPP' presence"
-if [[ "$PH_STOPAPP_STATE" == "Running" ]]
-then
-	printf "%10s\033[32m%s\033[0m\n\n" "" "OK (Found) -> Stopping"
-	ph_set_result -r 0
-	ph_show_result
-	ph_set_result -t -r "$?"
-	printf "\033[36m%s\033[0m\n\n" "- Executing '$PH_STOPAPP' stop action"
-        [[ -z "$1" && "$("$PH_SUDO" cat "/proc/$PPID/comm")" != @(start*sh|+(?)to+(?).sh|restart!("$PH_STOPAPPL").sh) ]] && \
+printf "\n\033[1;36m%s\033[0;0m\n\n" "- Stopping '${PH_STOPAPP}'"
+printf "%8s%s\033[1;33m%s\033[0;0m\n" "" "--> Checking the requirements to stop " "'${PH_STOPAPP}'"
+PH_STOPAPP_STATE="$(ph_get_app_state_from_app_name "${PH_STOPAPP}")"
+case "${PH_STOPAPP_STATE}" in Supported|Integrated|Halted)
+	ph_run_with_rollback -c true -m "Nothing to do"
+	ph_show_result ;;
+		Running)
+	ph_run_with_rollback -c true
+	[[ -z "${PH_PARAM}" && "$("${PH_SUDO}" cat "/proc/${PPID}/comm" 2>/dev/null)" != @(start*sh|+(?)to+(?).sh|restart!("${PH_STOPAPPL}").sh) ]] && \
 			PH_PARAM="force"
-	ph_do_app_action stop "$PH_STOPAPP" $PH_PARAM
-	ph_show_result
-	ph_set_result -t -r "$?"
-else
-	printf "%10s\033[33m%s\033[0m\n\n" "" "Warning : Not found"
-	ph_set_result -r 0 -w -m "'TTY$PH_STOPAPP_TTY' allocated to '$PH_STOPAPP' already stopped"
-	ph_show_result
-	exit "$?"
-fi
-ph_show_result -t
-exit "$?"
+	if ph_do_app_action stop "${PH_STOPAPP}" ${PH_PARAM}
+	then
+		ph_show_result
+	fi ;;
+		*)
+	ph_set_result -m "Could not stop '${PH_STOPAPP}' since it's not a supported application"
+	ph_run_with_rollback -c false -m "Could not stop" ;;
+esac
+exit "${?}"
diff --git a/files/templates/StopScriptPieH.template b/files/templates/StopScriptPieH.template
--- a/files/templates/StopScriptPieH.template
+++ b/files/templates/StopScriptPieH.template
@@ -2,139 +2,131 @@
 # Run '#PH_APP#' stop action (by Davy Keppens on 04/10/2018)
 # Enable/Disable debug by running 'confpieh_ph.sh -p debug -m stop#PH_APPL#.sh'
 
-. "$(dirname "$0" 2>/dev/null)/app/main.sh" || \
-	exit "$?" && \
+. "$(dirname "${0}" 2>/dev/null)/app/main.sh" || \
+	exit "${?}" && \
 	set +x
 
 #set -x
 
-declare PH_STOPAPP="#PH_APP#"
-declare PH_STOPAPP_STATE=""
-declare PH_PARAM=""
-declare PH_OPTION=""
-declare PH_INST=""
-declare PH_MODE=""
-declare PH_i=""
-declare PH_OLDOPTARG="$OPTARG"
-declare -i PH_OLDOPTIND="$OPTIND"
-declare -i PH_RET_CODE="0"
-declare -i PH_STOPAPP_TTY="0"
-declare -l PH_STOPAPPL="${PH_STOPAPP:0:4}"
+declare PH_i
+declare PH_STOPAPP
+declare PH_STOPAPP_STATE
+declare PH_PARAM
+declare PH_MODE
+declare PH_INST
+declare PH_OPTION
+declare PH_OLDOPTARG
+declare -i PH_OLDOPTIND
+declare -i PH_STOPAPP_TTY
+declare -l PH_STOPAPPL
+
+PH_i=""
+PH_STOPAPP="#PH_APP#"
+PH_STOPAPP_STATE=""
+PH_PARAM=""
+PH_MODE=""
+PH_INST=""
+PH_OPTION=""
+PH_OLDOPTARG="${OPTARG}"
+PH_OLDOPTIND="${OPTIND}"
+PH_STOPAPP_TTY="0"
+PH_STOPAPPL="${PH_STOPAPP:0:4}"
 
 OPTIND="1"
 
-while getopts pfh PH_OPTION 2>/dev/null
+while getopts :pfh PH_OPTION
 do
-        case "$PH_OPTION" in p)
-		[[ -n "$PH_MODE" ]] && (! "stop$PH_STOPAPPL.sh" -h) && OPTIND="$PH_OLDOPTIND" && \
-			OPTARG="$PH_OLDOPTARG" && exit 1
+        case "${PH_OPTION}" in p)
+		[[ -n "${PH_MODE}" ]] && \
+			(! "stop${PH_STOPAPPL}.sh" -h) && \
+			OPTIND="${PH_OLDOPTIND}" && \
+			OPTARG="${PH_OLDOPTARG}" && \
+			exit 1
 		PH_MODE="pseudo" ;;
                              f)
-		[[ -n "$PH_PARAM" ]] && (! "stop$PH_STOPAPPL.sh" -h) && OPTIND="$PH_OLDOPTIND" && \
-			OPTARG="$PH_OLDOPTARG" && exit 1
+		[[ -n "${PH_PARAM}" ]] && \
+			(! "stop${PH_STOPAPPL}.sh" -h) && \
+			OPTIND="${PH_OLDOPTIND}" && \
+			OPTARG="${PH_OLDOPTARG}" && \
+			exit 1
 		PH_PARAM="force" ;;
                              *)
-                >&2 printf "\n\033[36m%s%s%s\033[0m\n" "Usage : stop" "$PH_STOPAPPL.sh" " '-p' | -h"
+                >&2 printf "\n\033[1;36m%s\033[0;0m\n" "Usage : stop${PH_STOPAPPL}.sh '-p' | -h"
                 >&2 printf "\n"
-                >&2 printf "%3s%s\n" "" "Where -h displays this usage"
-                >&2 printf "%9s%s\n" "" "- Running this script without parameters will stop an instance of '$PH_STOPAPP' running on it's allocated TTY"
-                >&2 printf "%12s%s\n" "" "- A TTY is only deallocated when an application is removed from PieHelper"
-                >&2 printf "%12s%s\n" "" "- Additionally, the following rules apply to the stop of '$PH_STOPAPP' :"
-                >&2 printf "%15s%s\n" "" "- If a '$PH_STOPAPP' instance is running on a pseudo-terminal, stop will fail"
-                >&2 printf "%15s%s\n" "" "- If no active instance of '$PH_STOPAPP' can be found on it's allocated TTY or"
-                >&2 printf "%15s%s\n" "" "  the TTY for '$PH_STOPAPP' cannot be determined, stop will be skipped but succeed with a warning"
-                >&2 printf "%9s%s\n" "" "-p allows setting the stop of '$PH_STOPAPP' to be executed on a pseudo-terminal instead of it's allocated TTY"
+                >&2 printf "%3s\033[1;37m%s\n" "" "Where -h displays this usage"
+                >&2 printf "%9s%s\n" "" "- Running this script without parameters will stop an instance of '${PH_STOPAPP}' running on its allocated tty"
+                >&2 printf "%12s%s\n" "" "- A tty is only deallocated when an application is removed from PieHelper"
+                >&2 printf "%12s%s\n" "" "- Additionally, the following rules apply to the stop of '${PH_STOPAPP}' :"
+                >&2 printf "%15s%s\n" "" "- If a '${PH_STOPAPP}' instance is running on a pseudo-terminal, stop will fail"
+                >&2 printf "%15s%s\n" "" "- If no active instance of '${PH_STOPAPP}' can be found on its allocated tty or"
+                >&2 printf "%15s%s\n" "" "  the tty for '${PH_STOPAPP}' cannot be determined, stop will be skipped but succeed with a warning"
+                >&2 printf "%9s%s\n" "" "-p allows setting the stop of '${PH_STOPAPP}' to be executed on a pseudo-terminal instead of its allocated tty"
                 >&2 printf "%12s%s\n" "" "- Specifying -p is optional"
                 >&2 printf "%12s%s\n" "" "- The following rules replace these for a normal stop :"
-                >&2 printf "%15s%s\n" "" "- If a '$PH_STOPAPP' instance is running on it's allocated TTY, stop will fail"
-                >&2 printf "%15s%s\n" "" "- If no active instance of '$PH_STOPAPP' can be found on a pseudo-terminal, stop will be skipped but succeed with a warning"
+                >&2 printf "%15s%s\n" "" "- If a '${PH_STOPAPP}' instance is running on its allocated tty, stop will fail"
+                >&2 printf "%15s%s\033[0;0m\n" "" "- If no active instance of '${PH_STOPAPP}' can be found on a pseudo-terminal, stop will be skipped but succeed with a warning"
                 >&2 printf "\n"
-                OPTIND="$PH_OLDOPTIND"
-		OPTARG="$PH_OLDOPTARG"
+                OPTIND="${PH_OLDOPTIND}"
+		OPTARG="${PH_OLDOPTARG}"
 		exit 1 ;;
         esac
 done
-OPTIND="$PH_OLDOPTIND"
-OPTARG="$PH_OLDOPTARG"
+OPTIND="${PH_OLDOPTIND}"
+OPTARG="${PH_OLDOPTARG}"
 
-[[ -z "$PH_MODE" ]] && PH_MODE="normal"
-
-printf "\n\033[36m%s\033[0m\n\n" "- Executing '$PH_STOPAPP' stop action prechecks"
-PH_STOPAPP_STATE="$(ph_get_app_state_from_app_name "$PH_STOPAPP")"
-printf "%8s%s\n" "" "--> Checking for '$PH_STOPAPP' integration"
-if [[ "$PH_STOPAPP_STATE" == @(Integrated|Halted|Running) ]]
-then
-	ph_set_result -r "$?"
-	printf "%10s\033[32m%s\033[0m\n" "" "OK ('$PH_STOPAPP_STATE')"
-else
-	ph_set_result -r "$?" -m "Integration is mandatory for '$PH_STOPAPP' stop"
-	printf "%10s\033[31m%s\033[0m\n" "" "ERROR : Invalid application state"
-	ph_show_result
-	exit "$?"
-fi
-printf "%8s%s\n" "" "--> Determining '$PH_STOPAPP' TTY"
-PH_STOPAPP_TTY="$(ph_get_app_tty_from_app_name "$PH_STOPAPP")"
-if [[ "$PH_STOPAPP_TTY" -le "1" || "$PH_STOPAPP_TTY" -gt "$PH_PIEH_MAX_TTYS" ]]
-then
-	printf "%10s\033[33m%s\033[0m\n\n" "" "Warning : Could not determine TTY"
-	ph_set_result -r 0 -w -m "A valid TTY allocation is mandatory for '$PH_STOPAPP' stop"
-	ph_show_result
-	exit "$?"
-else
-	printf "%10s\033[32m%s\033[0m\n" "" "OK ('TTY$PH_STOPAPP_TTY')"
-	ph_set_result -r 0
-fi
-printf "%8s%s\n" "" "--> Checking for '$PH_STOPAPP' presence"
-PH_INST="$(pgrep ^"start$PH_STOPAPPL.sh" 2>/dev/null | sed "s/^""$PPID""$//g" | paste -d" " -s)"
-if [[ -z "$PH_INST" ]]
-then
-	printf "%10s\033[33m%s\033[0m\n" "" "Warning : Not found"
-	ph_set_result -r 0 -w -m "'TTY$PH_STOPAPP_TTY' allocated to '$PH_STOPAPP' already stopped"
-	ph_show_result
-	exit "$?"
-fi
-pgrep -t "tty$PH_STOPAPP_TTY" -f "start$PH_STOPAPPL.sh" >/dev/null 2>&1
-case "$?"_"$PH_MODE" in 0_normal)
-	printf "%10s\033[32m%s\033[0m\n" "" "OK (Found on a TTY)"
-	ph_set_result -r 0
-	ph_show_result
-	ph_set_result -t -r "$?"
-	printf "\033[36m%s\033[0m\n\n" "- Executing '$PH_STOPAPP' stop action on a TTY"
-        [[ -z "$1" && "$("$PH_SUDO" cat "/proc/$PPID/comm")" != @(start*sh|+(?)to+(?).sh|restart!("$PH_STOPAPPL").sh) ]] && \
-                        PH_PARAM="force"
-	ph_do_app_action stop "$PH_STOPAPP" $PH_PARAM ;;
-			1_normal)
-	printf "%10s\033[31m%s\033[0m\n" "" "ERROR : Invalid mode"
-	ph_set_result -r 1 -m "Using option '-p' is mandatory for '$PH_STOPAPP' stop on a pseudo-terminal"
-	ph_show_result
-	exit "$?" ;;
-			0_pseudo)
-	printf "%10s\033[31m%s\033[0m\n" "" "ERROR : Invalid mode"
-	ph_set_result -r 1 -m "Not using option '-p' is mandatory for '$PH_STOPAPP' stop on a TTY"
-	ph_show_result
-	exit "$?" ;;
-			1_pseudo)
-	printf "%10s\033[32m%s\033[0m\n" "" "OK (Found on a pseudo-terminal)"
-	ph_set_result -r 0
-	ph_show_result
-	ph_set_result -t -r "$?"
-	printf "\033[36m%s\033[0m\n\n" "- Executing '$PH_STOPAPP' stop action on a pseudo-terminal"
-	printf "%8s%s\n" "" "--> Stopping '$PH_STOPAPP' on a pseudo-terminal"
-	for PH_i in $(echo -n "$PH_INST")
-	do
-		"$PH_SUDO" kill "$PH_i" 2>/dev/null
-		[[ "$?" -ne "0" ]] && PH_RET_CODE="1"
-	done
-	if [[ "$PH_RET_CODE" -eq "0" ]]
+[[ -z "${PH_MODE}" ]] && \
+	PH_MODE="normal"
+printf "\n\033[1;36m%s\033[0;0m\n\n" "- Stopping '${PH_STOPAPP}'"
+printf "%8s%s\033[1;33m%s\033[0;0m\n" "" "--> Checking the requirements to stop " "'${PH_STOPAPP}'"
+PH_STOPAPP_STATE="$(ph_get_app_state_from_app_name "${PH_STOPAPP}")"
+case "${PH_STOPAPP_STATE}" in Supported|Integrated|Halted)
+	ph_run_with_rollback -c true -m "Nothing to do"
+	ph_show_result ;;
+		Running)	
+	ph_run_with_rollback -c true
+	printf "%8s%s\033[1;33m%s\033[0;0m\n" "" "--> Determining the tty of " "'${PH_STOPAPP}'"
+	PH_STOPAPP_TTY="$(ph_get_app_tty_from_app_name "${PH_STOPAPP}")"
+	ph_run_with_rollback -c true -m "tty${PH_STOPAPP_TTY}"
+	printf "%8s%s\n" "" "--> Checking wether '${PH_STOPAPP}' is running on its tty"
+	if pgrep -t "tty${PH_STOPAPP_TTY}" -f "start${PH_STOPAPPL}.sh" >/dev/null 2>&1
 	then
-		printf "%10s\033[32m%s\033[0m\n" "" "OK"
-		ph_set_result -r 0
+		if [[ "${PH_MODE}" == "normal" ]]
+		then
+			ph_run_with_rollback -c true -m yes
+			[[ -z "${PH_PARAM}" && "$("${PH_SUDO}" cat "/proc/${PPID}/comm" 2>/dev/null)" != @(start*sh|+(?)to+(?).sh|restart!("${PH_STOPAPPL}").sh) ]] && \
+				PH_PARAM="force"
+			if ph_do_app_action stop "${PH_STOPAPP}" ${PH_PARAM}
+			then
+				ph_show_result
+			fi
+		else
+			ph_set_result -m "Could not stop '${PH_STOPAPP}' since it's running on a tty -> Do not use option '-p'"
+			ph_run_with_rollback -c false -m "Could not stop '${PH_STOPAPP}' on its tty"
+		fi
 	else
-		printf "%10s\033[31m%s\033[0m\n" "" "ERROR : Could not stop application"
-		ph_set_result -r 1 -m "An error occurred stopping '$PH_STOPAPP' on a pseudo-terminal"
+		if [[ "${PH_MODE}" == "normal" ]]
+		then
+			ph_set_result -m "Could not stop '${PH_STOPAPP}' since it's running on a pseudo-terminal -> Use option '-p'"
+			ph_run_with_rollback -c false -m "Could not stop"
+		else
+			ph_run_with_rollback -c true -m no
+			printf "%8s%s\033[1;33m%s\033[0;0m\n" "" "--> Stopping " "'${PH_STOPAPP}'"
+			PH_INST="$(pgrep "^start${PH_STOPAPPL}.sh" 2>/dev/null | sed "s/^${PPID}$//g" | paste -d" " -s)"
+			for PH_i in ${PH_INST}
+			do
+				if ! "${PH_SUDO}" kill -9 "${PH_i}" 2>/dev/null
+				then
+					ph_set_result -m "An error occurred trying to kill process ID '${PH_i}'"
+					ph_run_with_rollback -c false -m "Could not stop '${PH_STOPAPP}' on a pseudo-terminal" || \
+						exit 1
+				fi
+			done
+			ph_run_with_rollback -c true
+			ph_show_result
+		fi
 	fi ;;
+		*)	
+	ph_set_result -m "Could not stop '${PH_STOPAPP}' since it's not a supported application"
+	ph_run_with_rollback -c false -m "Could not stop" ;;
 esac
-ph_show_result
-ph_set_result -t -r "$?"
-ph_show_result -t
-exit "$?"
+exit "${?}"
