More changes

diff --git a/files/templates/StartScript.template b/files/templates/StartScript.template
--- a/files/templates/StartScript.template
+++ b/files/templates/StartScript.template
@@ -2,9 +2,19 @@
 # Run '#PH_APP#' start action (by Davy Keppens on 04/10/2018)
 # Enable/Disable debug by running 'confpieh_ph.sh -p debug -m start#PH_APPL#.sh'
 
-. "$(dirname "${0}" 2>/dev/null)/app/main.sh" || \
-	exit 1 && \
+if [[ -e "$(dirname "${0}" 2>/dev/null)/app/main.sh" && -r "$(dirname "${0}" 2>/dev/null)/app/main.sh" ]]
+then
+	if ! source "$(dirname "${0}" 2>/dev/null)/app/main.sh"
+	then
+		set +x
+		printf "\n%2s\033[1;31m%s\033[0m\n\n" "" "ABORT : Reinstallation of PieHelper is required (Corrupted critical codebase file '$(dirname "${0}" 2>/dev/null)/app/main.sh'"
+		exit 1
+	fi
 	set +x
+else
+	printf "\n%2s\033[1;31m%s\033[0m\n\n" "" "ABORT : Reinstallation of PieHelper is required (Missing or unreadable critical codebase file '$(dirname "${0}" 2>/dev/null)/app/main.sh'"
+	exit 1
+fi
 
 #set -x
 
